local icons = {
  plugins = {
    cmd = " ",
    debug = " ",
    event = " ",
    keys = "󰌆 ",
    loaded = "",
    not_loaded = "",
    plugin = "󰏔 ",
    runtime = " ",
    source = "󰘬 ",
    start = " ",
  },
  debugger = {
    play = "",
    pause = "",
    step_into = "󰆹",
    step_over = "",
    step_out = "",
    step_back = "",
    run_last = "",
    terminate = "",
    disconnect = "",
  },
  outline = {
    Class = "󰠱",
    Function = "󰊕",
    Method = "󰖷",
    Interface = "",
    Struct = "",
    Array = "󰅨",
    Constructor = "",
    Enum = "",
    Module = "󰐱",
  },
  completion = {
    Array = "󰅨",
    Boolean = "",
    Class = "󰠱",
    Color = "󰏘",
    Constant = "󰏿",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    File = "",
    Folder = "",
    Function = "󰊕",
    Interface = "",
    Key = "󰌆",
    Keyword = "󰌆",
    Method = "󰖷",
    Module = "󰐱",
    Null = "",
    Number = "",
    Package = "󰏔",
    Property = "󰖷",
    Snippet = "",
    Struct = "",
    Text = "󰉿",
    Unit = "",
  },
  manager = {
    package_installed = "",
    package_pending = "",
    package_uninstalled = "",
  },
  icons = {
    default = {
      file = { glyph = "", },
    },
    directory = {},
    extension = {},
    file = {
      ["init.lua"] = { glyph = "", hl = "MiniIconsAzure", },
      ["LICENSE"] = { glyph = "󱈤", },
      ["LICENSE.txt"] = { glyph = "󱈤", },
      ["README"] = { glyph = "󰯂", },
      ["README.md"] = { glyph = "󰯂", },
    },
    filetype = {
      sh = { glyph = "", hl = "MiniIconsGreen", },
      go = { glyph = "", hl = "MiniIconsAzure", },
      python = { glyph = "", hl = "MiniIconsYellow", },
      c = { glyph = "", hl = "MiniIconsBlue", },
      cpp = { glyph = "", hl = "MiniIconsBlue", },
      markdown = { glyph = "󰈚", },
      text = { glyph = "󰈚", },
    },
    lsp = {},
    os = {},
  },
  notifications = {
    TRACE = "",
    DEBUG = "",
    INFO = "",
    WARN = "",
    ERROR = "",
  },
  breadcrumbs = {
    Array = "󰅨 ",
    BlockMappingPair = "󰅩 ",
    Boolean = " ",
    BreakStatement = "󰙧 ",
    Call = "󰃷 ",
    CaseStatement = "󱃙 ",
    Class = "󰠱 ",
    Color = "󰏘 ",
    Constant = "󰏿 ",
    Constructor = " ",
    ContinueStatement = "→ ",
    Copilot = " ",
    Declaration = "󰙠 ",
    Delete = "󰩺 ",
    DoStatement = "󰑖 ",
    Element = "󰅩 ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = "󰈔 ",
    Folder = "󰉋 ",
    ForStatement = "󰑖 ",
    Function = "󰊕 ",
    GotoStatement = "󰁔 ",
    Identifier = "󰀫 ",
    IfStatement = "󰇉 ",
    Interface = " ",
    Keyword = "󰌋 ",
    List = "󰅪 ",
    Log = "󰦪 ",
    Lsp = " ",
    Macro = "󰁌 ",
    MarkdownH1 = "󰉫 ",
    MarkdownH2 = "󰉬 ",
    MarkdownH3 = "󰉭 ",
    MarkdownH4 = "󰉮 ",
    MarkdownH5 = "󰉯 ",
    MarkdownH6 = "󰉰 ",
    Method = "󰆧 ",
    Module = "󰏗 ",
    Namespace = "󰅩 ",
    Null = "󰢤 ",
    Number = "󰎠 ",
    Object = "󰅩 ",
    Operator = "󰆕 ",
    Package = "󰆦 ",
    Pair = "󰅪 ",
    Property = " ",
    Reference = "󰦾 ",
    Regex = " ",
    Repeat = "󰑖 ",
    Return = "󰌑 ",
    Rule = "󰅩 ",
    RuleSet = "󰅩 ",
    Scope = "󰅩 ",
    Section = "󰅩 ",
    Snippet = "󰩫 ",
    Specifier = "󰦪 ",
    Statement = "󰅩 ",
    String = "󰉾 ",
    Struct = " ",
    SwitchStatement = "󰺟 ",
    Table = "󰅩 ",
    Terminal = " ",
    Text = " ",
    Type = " ",
    TypeParameter = "󰆩 ",
    Unit = " ",
    Value = "󰎠 ",
    Variable = "󰀫 ",
    WhileStatement = "󰑖 ",
  },
  -- explorer = {
  --   folder = {
  --     arrow_closed = " ",
  --     arrow_open = " ",
  --     default = "",
  --     open = "",
  --     empty = "",
  --     empty_open = "",
  --     symlink = "",
  --     symlink_open = "",
  --   },
  --   git = {
  --     staged = "",
  --     unstaged = "",
  --     unmerged = "",
  --     deleted = "",
  --     ignored = "",
  --     renamed = "",
  --     untracked = "",
  --   },
  -- },
}


return icons
