require("lazy").setup {
  ui = {
    border = "rounded",
    size = {
      width = 0.75,
      height = 0.75,
    },
    icons = require("util.icons").plugins,
  },
  spec = {
    -- plugins --
    require("plugins.autocomplete"),
    require("plugins.autopairs"),
    require("plugins.colorizer"),
    require("plugins.colorscheme"),
    require("plugins.context"),
    require("plugins.dashboard"),
    require("plugins.debugger"),
    require("plugins.explorer"),
    require("plugins.finder"),
    require("plugins.formatter"),
    require("plugins.icons"),
    require("plugins.indents"),
    require("plugins.lsp"),
    require("plugins.manager"),
    require("plugins.notifications"),
    require("plugins.references"),
    require("plugins.scrollbar"),
    require("plugins.session"),
    require("plugins.signature"),
    require("plugins.statusline"),
    require("plugins.surround"),
    require("plugins.syntax"),
    require("plugins.terminal"),
    require("plugins.test"),
    require("plugins.textobjects"),
    require("plugins.todocomments"),
    require("plugins.troubleshoots"),
    require("plugins.vcs"),
    require("plugins.winbar"),
    require("plugins.zenmode"),

    -- languages --
    require("languages.rust").plugins,
  },
}
