return {
  plugins = {
    cmd = " ",
    debug = " ",
    event = " ",
    keys = "󰌆 ",
    loaded = "",
    not_loaded = "",
    plugin = "󰏔 ",
    runtime = " ",
    source = "󰘬 ",
    start = " ",
  },
  debugger = {
    play = "",
    pause = "",
    step_into = "󰆹",
    step_over = "",
    step_out = "",
    step_back = "",
    run_last = "",
    terminate = "",
    disconnect = "",
  },
  autocomplete = {
    Array = "󰅨",
    Boolean = "",
    Class = "󰠱",
    Color = "󰏘",
    Constant = "󰏿",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    File = "",
    Folder = "",
    Function = "󰊕",
    Interface = "",
    Key = "󰌆",
    Keyword = "󰌆",
    Method = "󰖷",
    Module = "󰐱",
    Null = "",
    Number = "",
    Package = "󰏔",
    Property = "󰖷",
    Snippet = "",
    Struct = "",
    Text = "󰉿",
    Unit = "",
  },
  manager = {
    package_installed = "",
    package_pending = "",
    package_uninstalled = "",
  },
  icons = {
    default = {
      file = {
        glyph = "",
        hl = "MiniIconsGrey",
      },
    },
    directory = {},
    extension = {},
    file = {
      ["init.lua"] = {
        glyph = "",
        hl = "MiniIconsAzure",
      },
      ["README"] = {
        glyph = "󰯂",
        hl = "MiniIconsYellow",
      },
      ["README.md"] = {
        glyph = "󰯂",
        hl = "MiniIconsYellow",
      },
    },
    filetype = {
      sh = {
        glyph = "",
        hl = "MiniIconsGreen",
      },
      go = {
        glyph = "",
        hl = "MiniIconsAzure",
      },
      python = {
        glyph = "",
        hl = "MiniIconsYellow",
      },
      c = {
        glyph = "",
        hl = "MiniIconsBlue",
      },
      cpp = {
        glyph = "",
        hl = "MiniIconsBlue",
      },
    },
    lsp = {},
    os = {},
  },
  notifications = {
    TRACE = "TRACE",
    DEBUG = "DEBUG",
    INFO = "INFO",
    WARN = "WARN",
    ERROR = "ERROR",
  },
}
