# base settings
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs prompt_char)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)


# os icon settings
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION="$USER"
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND="#89b4fa"
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=""


# dir settings
typeset -g POWERLEVEL9K_DIR_CLASSES=(
  "/"                ROOT    ""
  "~"                HOME    ""
  "*"                DEFAULT ""
)
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=""
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_DIR_FOREGROUND="#94e2d5"
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND="#94e2d5"
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="#94e2d5"
typeset -g POWERLEVEL9K_DIR_BACKGROUND=""
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND=""
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=""


# separator settings
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=""
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=""
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=""
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=""
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""


# whitespace settings
typeset -g POWERLEVEL9K_OS_ICON_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_OS_ICON_LEFT_RIGHT_WHITESPACE=""
typeset -g POWERLEVEL9K_DIR_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_DIR_LEFT_RIGHT_WHITESPACE=""
typeset -g POWERLEVEL9K_VCS_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_VCS_LEFT_RIGHT_WHITESPACE=""
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_RIGHT_WHITESPACE=""
typeset -g POWERLEVEL9K_TIME_RIGHT_LEFT_WHITESPACE=""
typeset -g POWERLEVEL9K_TIME_RIGHT_RIGHT_WHITESPACE=""


# enable line spacing
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true


# transient prompt settings
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT_LEFT_PROMPT_ELEMENTS=(prompt_char)
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT_RIGHT_PROMPT_ELEMENTS=()
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_CONTENT_EXPANSION="•"
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_FOREGROUND="#ffffff"
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_BACKGROUND=""


# disable two-line prompt
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_LPROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false


# lines separator settings
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=""
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=""
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_FOREGROUND=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_FOREGROUND=""
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX_FOREGROUND=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX_FOREGROUND=""


# command execution time settings
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT="d h m s"
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=""
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=""
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON=""
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=""


# time settings
typeset -g POWERLEVEL9K_TIME_FORMAT="%D{%I:%M:%S %p}"
typeset -g POWERLEVEL9K_TIME_FOREGROUND="#f5e0dc"
typeset -g POWERLEVEL9K_TIME_BACKGROUND=""
typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=""


# vcs settings
typeset -g POWERLEVEL9K_VCS_FOREGROUND="#f5e0dc"
typeset -g POWERLEVEL9K_VCS_BACKGROUND=""
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION="on "
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=""
typeset -g POWERLEVEL9K_VCS_MODIFIED_ICON="!"
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON="󰆢"
typeset -g POWERLEVEL9K_VCS_ADDED_ICON=""
typeset -g POWERLEVEL9K_VCS_RENAMED_ICON="󰑕"
typeset -g POWERLEVEL9K_VCS_DELETED_ICON=""
typeset -g POWERLEVEL9K_VCS_CONFLICT_ICON=""
typeset -g POWERLEVEL9K_VCS_STASH_ICON=""
