prefix := "/usr/local"
cc := "gcc"

default:
  @just --list

build:
  @{{cc}} -c dwmblocks.c
  @{{cc}} dwmblocks.o -lX11 -o dwmblocks

clean:
  @rm -f dwmblocks.o dwmblocks

install: build
  @mkdir -p {{prefix}}/bin
  @cp dwmblocks {{prefix}}/bin
  @chmod 755 {{prefix}}/bin/dwmblocks

uninstall:
  @rm -f {{prefix}}/bin/dwmblocks
