require("lazy").setup {
  ui = {
    border = "rounded",
    size = {
      width = 0.75,
      height = 0.75,
    },
    icons = {
      cmd = " ",
      debug = " ",
      event = " ",
      keys = "󰌆 ",
      loaded = "",
      not_loaded = "",
      plugin = "󰏔 ",
      runtime = " ",
      source = "󰘬 ",
      start = " ",
    },
  },
  spec = {
    -- plugins --
    require("whyhilde.plugins.autocomplete"),
    require("whyhilde.plugins.autopairs"),
    require("whyhilde.plugins.colorizer"),
    require("whyhilde.plugins.context"),
    require("whyhilde.plugins.dashboard"),
    require("whyhilde.plugins.debugger"),
    require("whyhilde.plugins.explorer"),
    require("whyhilde.plugins.finder"),
    require("whyhilde.plugins.formatter"),
    require("whyhilde.plugins.icons"),
    require("whyhilde.plugins.indents"),
    require("whyhilde.plugins.lsp"),
    require("whyhilde.plugins.manager"),
    require("whyhilde.plugins.notifications"),
    require("whyhilde.plugins.references"),
    require("whyhilde.plugins.scrollbar"),
    require("whyhilde.plugins.session"),
    require("whyhilde.plugins.signature"),
    require("whyhilde.plugins.snippets"),
    require("whyhilde.plugins.statusline"),
    require("whyhilde.plugins.surround"),
    require("whyhilde.plugins.syntax"),
    require("whyhilde.plugins.terminal"),
    require("whyhilde.plugins.tests"),
    require("whyhilde.plugins.textobjects"),
    require("whyhilde.plugins.todocomments"),
    require("whyhilde.plugins.troubleshoots"),
    require("whyhilde.plugins.vcs"),
    require("whyhilde.plugins.winbar"),
    require("whyhilde.plugins.zenmode"),

    -- colorschemes --
    require("whyhilde.colorschemes.gruvbox"),
    require("whyhilde.colorschemes.catppuccin"),
  },
}
