return {
  "lewis6991/gitsigns.nvim",
  event = {
    "BufReadPre",
    "BufNewFile",
    "BufNew",
  },
  opts = {
    signs = {
      add = { text = "┃" },
      change = { text = "┃" },
      delete = { text = "-" },
      topdelete = { text = "-" },
      changedelete = { text = "~" },
      untracked = { text = "¦" },
    },
    signs_staged_enable = true,
    signs_staged = {
      add = { text = "┃" },
      change = { text = "┃" },
      delete = { text = "-" },
      topdelete = { text = "-" },
      changedelete = { text = "~" },
      untracked = { text = "¦" },
    },
    signcolumn = true,
    numhl = false,
    linehl = false,
    word_diff = false,
    diff_opts = {
      algorithm = "histogram",
      ignore_whitespace_change = true,
    },
    current_line_blame = false,
    current_line_blame_opts = {
      virt_text = true,
      virt_text_pos = "eol",
      delay = 100,
      ignore_whitespace = false,
    },
    current_line_blame_formatter = "<author>, <author_time:%d-%m-%y>: <summary>",
    attach_to_untracked = true,
    sign_priority = 6,
    update_debounce = 100,
    status_formatter = nil,
    max_file_length = 40000,
  },
  keys = {
    {
      mode = "n",
      "]c",
      "<cmd>Gitsigns next_hunk<cr>",
    },
    {
      mode = "n",
      "[c",
      "<cmd>Gitsigns prev_hunk<cr>",
    },
    {
      mode = "n",
      "<leader>hs",
      "<cmd>Gitsigns stage_hunk<cr>",
    },
    {
      mode = "n",
      "<leader>hr",
      "<cmd>Gitsigns reset_hunk<cr>",
    },
    {
      mode = "n",
      "<leader>hS",
      "<cmd>Gitsigns stage_buffer<cr>",
    },
    {
      mode = "n",
      "<leader>hR",
      "<cmd>Gitsigns reset_buffer<cr>",
    },
    {
      mode = "n",
      "<leader>hp",
      "<cmd>Gitsigns preview_hunk<cr>",
    },
    {
      mode = "n",
      "<leader>hb",
      "<cmd>Gitsigns blame_line<cr>",
    },
    {
      mode = "n",
      "<leader>tb",
      "<cmd>Gitsigns toggle_current_line_blame<cr>",
    },
    {
      mode = "n",
      "<leader>hd",
      "<cmd>Gitsigns diffthis<cr>",
    },
    {
      mode = "v",
      "<leader>hs",
      "<cmd>Gitsigns stage_hunk<cr>",
    },
    {
      mode = "v",
      "<leader>hr",
      "<cmd>Gitsigns reset_hunk<cr>",
    },
  },
}
