set -g mouse on
set -g set-clipboard on
set -g escape-time 0

# unbind C-b
# set -g prefix C-a
unbind-key -a -T root

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 3
bind -n M-K resize-pane -U 3
bind -n M-L resize-pane -R 5

bind -n M-s split-window -h
bind -n M-S split-window -v

bind -n M-Enter new-window
bind -n M-c kill-pane
bind -n M-q detach
bind -n M-Q confirm-before -p "kill session? (y/n)" kill-session
bind -n M-r source-file ~/.config/tmux/tmux.conf
bind -n M-t choose-tree -s

set-window-option -g mode-keys vi
bind-key -n M-v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane



light="#d3c6aa"
dark="#272e33"
gray="#414b50"
green="#a7c080"

set -g status-position top
set -g status-style "fg=${light},bg=default"
set -g status-left ""
set -g status-right "[ #S ]"
set -g window-status-format "#[fg=${gray}] #W "
set -g window-status-current-format "#[fg=${dark},bg=${green}] #W "
# set -g window-status-style "fg=${gray},bg=default"
# set -g window-status-activity-style "fg=${dark},bg=${green}"

set -g pane-border-style "fg=${gray}"
set -g pane-active-border-style "fg=${green}"

set -g message-style "fg=${light},bg=default"
set -g mode-style "fg=${dark},bg=${green}"
