local palette = {
  dark0 = "#1d2021",
  dark1 = "#3c3836",
  dark2 = "#504945",
  dark3 = "#665c54",
  dark4 = "#7c6f64",
  light0 = "#fbf1c7",
  light1 = "#ebdbb2",
  light2 = "#d5c4a1",
  light3 = "#bdae93",
  light4 = "#a89984",
  bright_red = "#ea6962",
  bright_green = "#a9b665",
  bright_yellow = "#d8a657",
  bright_blue = "#7daea3",
  bright_purple = "#d3869b",
  bright_aqua = "#89b482",
  bright_orange = "#e78a4e",
  neutral_red = "#cc241d",
  neutral_green = "#98971a",
  neutral_yellow = "#d79921",
  neutral_blue = "#458588",
  neutral_purple = "#b16286",
  neutral_aqua = "#689d6a",
  neutral_orange = "#d65d0e",
  faded_red = "#9d0006",
  faded_green = "#79740e",
  faded_yellow = "#b57614",
  faded_blue = "#076678",
  faded_purple = "#8f3f71",
  faded_aqua = "#427b58",
  faded_orange = "#af3a03",
  dark_red = "#722529",
  light_red = "#fc9487",
  dark_green = "#62693e",
  light_green = "#d5d39b",
  dark_aqua = "#49503b",
  light_aqua = "#e8e5b5",
  gray = "#928374",
}


local function get_colors()
  local p = palette
  local bg = vim.opt.background._value

  local color_groups = {
    dark = {
      bg0 = p.dark0,
      bg1 = p.dark1,
      bg2 = p.dark2,
      bg3 = p.dark3,
      bg4 = p.dark4,
      fg0 = p.light0,
      fg1 = p.light1,
      fg2 = p.light2,
      fg3 = p.light3,
      fg4 = p.light4,
      red = p.bright_red,
      green = p.bright_green,
      yellow = p.bright_yellow,
      blue = p.bright_blue,
      purple = p.bright_purple,
      aqua = p.bright_aqua,
      orange = p.bright_orange,
      -- neutral_red = p.neutral_red,
      -- neutral_green = p.neutral_green,
      -- neutral_yellow = p.neutral_yellow,
      -- neutral_blue = p.neutral_blue,
      -- neutral_purple = p.neutral_purple,
      -- neutral_aqua = p.neutral_aqua,
      -- dark_red = p.dark_red,
      -- dark_green = p.dark_green,
      -- dark_aqua = p.dark_aqua,
      gray = p.gray,
    },
    light = {
      bg0 = p.light0,
      bg1 = p.light1,
      bg2 = p.light2,
      bg3 = p.light3,
      bg4 = p.light4,
      fg0 = p.dark0,
      fg1 = p.dark1,
      fg2 = p.dark2,
      fg3 = p.dark3,
      fg4 = p.dark4,
      red = p.faded_red,
      green = p.faded_green,
      yellow = p.faded_yellow,
      blue = p.faded_blue,
      purple = p.faded_purple,
      aqua = p.faded_aqua,
      orange = p.faded_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.light_red,
      dark_green = p.light_green,
      dark_aqua = p.light_aqua,
      gray = p.gray,
    },
  }

  return color_groups[bg]
end


local function setup()
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "gruvbox"
  vim.o.termguicolors = true

  local colors = get_colors()
  local function hi(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- local term_colors = {
  --   colors.bg0,
  --   colors.neutral_red,
  --   colors.neutral_green,
  --   colors.neutral_yellow,
  --   colors.neutral_blue,
  --   colors.neutral_purple,
  --   colors.neutral_aqua,
  --   colors.fg4,
  --   colors.gray,
  --   colors.red,
  --   colors.green,
  --   colors.yellow,
  --   colors.blue,
  --   colors.purple,
  --   colors.aqua,
  --   colors.fg1,
  -- }
  --
  -- for index, value in ipairs(term_colors) do
  --   vim.g["terminal_color_" .. index - 1] = value
  -- end

  -- gruvbox
  hi("GruvboxFg0", { fg = colors.fg0 })
  hi("GruvboxFg1", { fg = colors.fg1 })
  hi("GruvboxFg2", { fg = colors.fg2 })
  hi("GruvboxFg3", { fg = colors.fg3 })
  hi("GruvboxFg4", { fg = colors.fg4 })
  hi("GruvboxBg0", { fg = colors.bg0 })
  hi("GruvboxBg1", { fg = colors.bg1 })
  hi("GruvboxBg2", { fg = colors.bg2 })
  hi("GruvboxBg3", { fg = colors.bg3 })
  hi("GruvboxBg4", { fg = colors.bg4 })
  hi("GruvboxRed", { fg = colors.red })
  hi("GruvboxGreen", { fg = colors.green })
  hi("GruvboxYellow", { fg = colors.yellow })
  hi("GruvboxBlue", { fg = colors.blue })
  hi("GruvboxPurple", { fg = colors.purple })
  hi("GruvboxAqua", { fg = colors.aqua })
  hi("GruvboxOrange", { fg = colors.orange })
  hi("GruvboxGray", { fg = colors.gray })

  -- general
  hi("Normal", { fg = colors.fg1, bg = nil })
  hi("NormalFloat", { fg = colors.fg1, bg = nil })
  hi("NormalNC", { link = "Normal" })
  hi("CursorLine", { bg = colors.bg1 })
  hi("CursorColumn", { link = "CursorLine" })
  hi("TabLineFill", { fg = colors.bg4, bg = "#141617" })
  hi("TabLineSel", { fg = colors.green, bg = nil })
  hi("TabLine", { link = "TabLineFill" })
  hi("MatchParen", { bg = colors.bg3 })
  hi("ColorColumn", { bg = colors.bg1 })
  hi("Conceal", { fg = colors.blue })
  hi("CursorLineNr", { link = "GruvboxOrange" })
  hi("NonText", { link = "GruvboxBg2" })
  hi("SpecialKey", { link = "GruvboxFg4" })
  hi("Visual", { bg = colors.bg1 })
  hi("VisualNOS", { link = "Visual" })
  hi("Search", { fg = colors.bg1, bg = colors.orange })
  hi("IncSearch", { link = "Search" })
  hi("CurSearch", { link = "IncSearch" })
  hi("QuickFixLine", { link = "GruvboxPurple" })
  hi("Underlined", { link = "GruvboxBlue" })
  hi("StatusLine", { fg = colors.fg1, bg = colors.bg2 })
  hi("StatusLineNC", { fg = colors.fg4, bg = colors.bg1 })
  hi("WinBar", { link = "Normal" })
  hi("WinBarNC", { link = "WinBar" })
  hi("WinSeparator", { link = "GruvboxBg3" })
  hi("WildMenu", { fg = colors.blue, bg = colors.bg2 })
  hi("Directory", { link = "GruvboxGreen" })
  hi("Title", { link = "GruvboxGreen" })
  hi("ErrorMsg", { fg = colors.bg0, bg = colors.red })
  hi("MoreMsg", { link = "GruvboxYellow" })
  hi("ModeMsg", { link = "GruvboxYellow" })
  hi("Question", { link = "GruvboxOrange" })
  hi("WarningMsg", { link = "GruvboxRed" })
  hi("LineNr", { link = "GruvboxBg4" })
  hi("SignColumn", { link = "Normal" })
  hi("Folded", { fg = colors.gray, bg = colors.bg1 })
  hi("FoldColumn", { fg = colors.gray, bg = nil })
  hi("Cursor", { reverse = true })
  hi("vCursor", { link = "Cursor" })
  hi("iCursor", { link = "Cursor" })
  hi("lCursor", { link = "Cursor" })
  hi("Special", { link = "GruvboxOrange" })
  hi("Comment", { link = "GruvboxGray" })
  hi("Todo", { fg = colors.bg0, bg = colors.yellow })
  hi("Done", { link = "GruvboxOrange" })
  hi("Error", { link = "GruvboxRed" })
  hi("Statement", { link = "GruvboxRed" })
  hi("Conditional", { link = "GruvboxRed" })
  hi("Repeat", { link = "GruvboxRed" })
  hi("Label", { link = "GruvboxRed" })
  hi("Exception", { link = "GruvboxRed" })
  hi("Operator", { link = "GruvboxFg2" })
  hi("Keyword", { link = "GruvboxRed" })
  hi("Identifier", { link = "GruvboxBlue" })
  hi("Function", { link = "GruvboxBlue" })
  hi("PreProc", { link = "GruvboxAqua" })
  hi("Include", { link = "GruvboxAqua" })
  hi("Define", { link = "GruvboxAqua" })
  hi("Macro", { link = "GruvboxAqua" })
  hi("PreCondit", { link = "GruvboxAqua" })
  hi("Constant", { link = "GruvboxPurple" })
  hi("Character", { link = "GruvboxPurple" })
  hi("String", { link = "GruvboxGreen" })
  hi("Boolean", { link = "GruvboxPurple" })
  hi("Number", { link = "GruvboxPurple" })
  hi("Float", { link = "GruvboxPurple" })
  hi("Type", { link = "GruvboxYellow" })
  hi("StorageClass", { link = "GruvboxOrange" })
  hi("Structure", { link = "GruvboxAqua" })
  hi("Typedef", { link = "GruvboxYellow" })
  hi("Pmenu", { fg = colors.fg1, bg = colors.bg2 })
  hi("PmenuSel", { fg = colors.bg2, bg = colors.blue })
  hi("PmenuSbar", { bg = colors.bg2 })
  hi("PmenuThumb", { bg = colors.bg4 })
  hi("PmenuKind", { link = "Pmenu" })
  -- hi("DiffDelete", { bg = colors.dark_red })
  -- hi("DiffAdd", { bg = colors.dark_green })
  -- hi("DiffChange", { bg = colors.dark_aqua })
  hi("DiffText", { bg = colors.yellow, fg = colors.bg0 })
  hi("SpellCap", { link = "GruvboxBlue" })
  hi("SpellBad", { link = "GruvboxRed" })
  hi("SpellLocal", { link = "GruvboxAqua" })
  hi("SpellRare", { link = "GruvboxPurple" })
  hi("Whitespace", { link = "GruvboxBg2" })
  hi("Delimiter", { link = "GruvboxFg2" })
  hi("EndOfBuffer", { link = "NonText" })
  hi("DiagnosticError", { link = "GruvboxRed" })
  hi("DiagnosticWarn", { link = "GruvboxYellow" })
  hi("DiagnosticInfo", { link = "GruvboxBlue" })
  hi("DiagnosticDeprecated", { strikethrough = true })
  hi("DiagnosticHint", { link = "GruvboxAqua" })
  hi("DiagnosticOk", { link = "GruvboxGreen" })
  hi("DiagnosticSignError", { link = "GruvboxRed" })
  hi("DiagnosticSignWarn", { link = "GruvboxYellow" })
  hi("DiagnosticSignInfo", { link = "GruvboxBlue" })
  hi("DiagnosticSignHint", { link = "GruvboxAqua" })
  hi("DiagnosticSignOk", { link = "GruvboxGreen" })
  hi("DiagnosticUnderlineError", { link = "GruvboxRed" })
  hi("DiagnosticUnderlineWarn", { link = "GruvboxYellow" })
  hi("DiagnosticUnderlineInfo", { link = "GruvboxBlue" })
  hi("DiagnosticUnderlineHint", { link = "GruvboxAqua" })
  hi("DiagnosticUnderlineOk", { link = "GruvboxGreen" })
  hi("DiagnosticFloatingError", { link = "GruvboxRed" })
  hi("DiagnosticFloatingWarn", { link = "GruvboxOrange" })
  hi("DiagnosticFloatingInfo", { link = "GruvboxBlue" })
  hi("DiagnosticFloatingHint", { link = "GruvboxAqua" })
  hi("DiagnosticFloatingOk", { link = "GruvboxGreen" })
  hi("DiagnosticVirtualTextError", { link = "GruvboxRed" })
  hi("DiagnosticVirtualTextWarn", { link = "GruvboxYellow" })
  hi("DiagnosticVirtualTextInfo", { link = "GruvboxBlue" })
  hi("DiagnosticVirtualTextHint", { link = "GruvboxAqua" })
  hi("DiagnosticVirtualTextOk", { link = "GruvboxGreen" })
  hi("LspReferenceRead", { link = "GruvboxYellow" })
  hi("LspReferenceTarget", { link = "Visual" })
  hi("LspReferenceText", { link = "GruvboxYellow" })
  hi("LspReferenceWrite", { link = "GruvboxOrange" })
  hi("LspCodeLens", { link = "GruvboxGray" })
  hi("LspSignatureActiveParameter", { link = "Search" })
  hi("LspInlayHint", { link = "Comment" })

  -- languages
  hi("htmlTag", { link = "GruvboxAqua" })
  hi("htmlEndTag", { link = "GruvboxAqua" })
  hi("htmlTagName", { link = "GruvboxBlue" })
  hi("htmlArg", { link = "GruvboxOrange" })
  hi("htmlTagN", { link = "GruvboxFg1" })
  hi("htmlSpecialTagName", { link = "GruvboxBlue" })
  hi("htmlLink", { link = "GruvboxFg4" })
  hi("htmlSpecialChar", { link = "GruvboxRed" })
  hi("htmlBold", { fg = colors.fg0, bg = colors.bg0 })
  hi("htmlBoldUnderline", { fg = colors.fg0, bg = colors.bg0 })
  hi("htmlBoldItalic", { fg = colors.fg0, bg = colors.bg0 })
  hi("htmlBoldUnderlineItalic", { fg = colors.fg0, bg = colors.bg0 })
  hi("htmlUnderline", { fg = colors.fg0, bg = colors.bg0 })
  hi("htmlUnderlineItalic", { fg = colors.fg0, bg = colors.bg0 })
  hi("htmlItalic", { fg = colors.fg0, bg = colors.bg0 })
  hi("xmlTag", { link = "GruvboxAqua" })
  hi("xmlEndTag", { link = "GruvboxAqua" })
  hi("xmlTagName", { link = "GruvboxBlue" })
  hi("xmlEqual", { link = "GruvboxBlue" })
  hi("docbkKeyword", { link = "GruvboxAqua" })
  hi("xmlDocTypeDecl", { link = "GruvboxGray" })
  hi("xmlDocTypeKeyword", { link = "GruvboxPurple" })
  hi("xmlCdataStart", { link = "GruvboxGray" })
  hi("xmlCdataCdata", { link = "GruvboxPurple" })
  hi("dtdFunction", { link = "GruvboxGray" })
  hi("dtdTagName", { link = "GruvboxPurple" })
  hi("xmlAttrib", { link = "GruvboxOrange" })
  hi("xmlProcessingDelim", { link = "GruvboxGray" })
  hi("dtdParamEntityPunct", { link = "GruvboxGray" })
  hi("dtdParamEntityDPunct", { link = "GruvboxGray" })
  hi("xmlAttribPunct", { link = "GruvboxGray" })
  hi("xmlEntity", { link = "GruvboxRed" })
  hi("xmlEntityPunct", { link = "GruvboxRed" })
  hi("clojureKeyword", { link = "GruvboxBlue" })
  hi("clojureCond", { link = "GruvboxOrange" })
  hi("clojureSpecial", { link = "GruvboxOrange" })
  hi("clojureDefine", { link = "GruvboxOrange" })
  hi("clojureFunc", { link = "GruvboxYellow" })
  hi("clojureRepeat", { link = "GruvboxYellow" })
  hi("clojureCharacter", { link = "GruvboxAqua" })
  hi("clojureStringEscape", { link = "GruvboxAqua" })
  hi("clojureException", { link = "GruvboxRed" })
  hi("clojureRegexp", { link = "GruvboxAqua" })
  hi("clojureRegexpEscape", { link = "GruvboxAqua" })
  hi("clojureRegexpCharClass", { link = "GruvboxFg3" })
  hi("clojureRegexpMod", { link = "clojureRegexpCharClass" })
  hi("clojureRegexpQuantifier", { link = "clojureRegexpCharClass" })
  hi("clojureParen", { link = "GruvboxFg3" })
  hi("clojureAnonArg", { link = "GruvboxYellow" })
  hi("clojureVariable", { link = "GruvboxBlue" })
  hi("clojureMacro", { link = "GruvboxOrange" })
  hi("clojureMeta", { link = "GruvboxYellow" })
  hi("clojureDeref", { link = "GruvboxYellow" })
  hi("clojureQuote", { link = "GruvboxYellow" })
  hi("clojureUnquote", { link = "GruvboxYellow" })
  hi("cOperator", { link = "GruvboxPurple" })
  hi("cppOperator", { link = "GruvboxPurple" })
  hi("cStructure", { link = "GruvboxOrange" })
  hi("pythonBuiltin", { link = "GruvboxOrange" })
  hi("pythonBuiltinObj", { link = "GruvboxOrange" })
  hi("pythonBuiltinFunc", { link = "GruvboxOrange" })
  hi("pythonFunction", { link = "GruvboxAqua" })
  hi("pythonDecorator", { link = "GruvboxRed" })
  hi("pythonInclude", { link = "GruvboxBlue" })
  hi("pythonImport", { link = "GruvboxBlue" })
  hi("pythonRun", { link = "GruvboxBlue" })
  hi("pythonCoding", { link = "GruvboxBlue" })
  hi("pythonOperator", { link = "GruvboxRed" })
  hi("pythonException", { link = "GruvboxRed" })
  hi("pythonExceptions", { link = "GruvboxPurple" })
  hi("pythonBoolean", { link = "GruvboxPurple" })
  hi("pythonDot", { link = "GruvboxFg3" })
  hi("pythonConditional", { link = "GruvboxRed" })
  hi("pythonRepeat", { link = "GruvboxRed" })
  hi("pythonDottedName", { link = "GruvboxGreen" })
  hi("cssBraces", { link = "GruvboxBlue" })
  hi("cssFunctionName", { link = "GruvboxYellow" })
  hi("cssIdentifier", { link = "GruvboxOrange" })
  hi("cssClassName", { link = "GruvboxGreen" })
  hi("cssColor", { link = "GruvboxBlue" })
  hi("cssSelectorOp", { link = "GruvboxBlue" })
  hi("cssSelectorOp2", { link = "GruvboxBlue" })
  hi("cssImportant", { link = "GruvboxGreen" })
  hi("cssVendor", { link = "GruvboxFg1" })
  hi("cssTextProp", { link = "GruvboxAqua" })
  hi("cssAnimationProp", { link = "GruvboxAqua" })
  hi("cssUIProp", { link = "GruvboxYellow" })
  hi("cssTransformProp", { link = "GruvboxAqua" })
  hi("cssTransitionProp", { link = "GruvboxAqua" })
  hi("cssPrintProp", { link = "GruvboxAqua" })
  hi("cssPositioningProp", { link = "GruvboxYellow" })
  hi("cssBoxProp", { link = "GruvboxAqua" })
  hi("cssFontDescriptorProp", { link = "GruvboxAqua" })
  hi("cssFlexibleBoxProp", { link = "GruvboxAqua" })
  hi("cssBorderOutlineProp", { link = "GruvboxAqua" })
  hi("cssBackgroundProp", { link = "GruvboxAqua" })
  hi("cssMarginProp", { link = "GruvboxAqua" })
  hi("cssListProp", { link = "GruvboxAqua" })
  hi("cssTableProp", { link = "GruvboxAqua" })
  hi("cssFontProp", { link = "GruvboxAqua" })
  hi("cssPaddingProp", { link = "GruvboxAqua" })
  hi("cssDimensionProp", { link = "GruvboxAqua" })
  hi("cssRenderProp", { link = "GruvboxAqua" })
  hi("cssColorProp", { link = "GruvboxAqua" })
  hi("cssGeneratedContentProp", { link = "GruvboxAqua" })
  hi("javaScriptBraces", { link = "GruvboxFg1" })
  hi("javaScriptFunction", { link = "GruvboxAqua" })
  hi("javaScriptIdentifier", { link = "GruvboxRed" })
  hi("javaScriptMember", { link = "GruvboxBlue" })
  hi("javaScriptNumber", { link = "GruvboxPurple" })
  hi("javaScriptNull", { link = "GruvboxPurple" })
  hi("javaScriptParens", { link = "GruvboxFg3" })
  hi("typescriptReserved", { link = "GruvboxAqua" })
  hi("typescriptLabel", { link = "GruvboxAqua" })
  hi("typescriptFuncKeyword", { link = "GruvboxAqua" })
  hi("typescriptIdentifier", { link = "GruvboxOrange" })
  hi("typescriptBraces", { link = "GruvboxFg1" })
  hi("typescriptEndColons", { link = "GruvboxFg1" })
  hi("typescriptDOMObjects", { link = "GruvboxFg1" })
  hi("typescriptAjaxMethods", { link = "GruvboxFg1" })
  hi("typescriptLogicSymbols", { link = "GruvboxFg1" })
  hi("typescriptDocSeeTag", { link = "Comment" })
  hi("typescriptDocParam", { link = "Comment" })
  hi("typescriptDocTags", { link = "vimCommentTitle" })
  hi("typescriptGlobalObjects", { link = "GruvboxFg1" })
  hi("typescriptParens", { link = "GruvboxFg3" })
  hi("typescriptOpSymbols", { link = "GruvboxFg3" })
  hi("typescriptHtmlElemProperties", { link = "GruvboxFg1" })
  hi("typescriptNull", { link = "GruvboxPurple" })
  hi("typescriptInterpolationDelimiter", { link = "GruvboxAqua" })
  hi("purescriptModuleKeyword", { link = "GruvboxAqua" })
  hi("purescriptModuleName", { link = "GruvboxFg1" })
  hi("purescriptWhere", { link = "GruvboxAqua" })
  hi("purescriptDelimiter", { link = "GruvboxFg4" })
  hi("purescriptType", { link = "GruvboxFg1" })
  hi("purescriptImportKeyword", { link = "GruvboxAqua" })
  hi("purescriptHidingKeyword", { link = "GruvboxAqua" })
  hi("purescriptAsKeyword", { link = "GruvboxAqua" })
  hi("purescriptStructure", { link = "GruvboxAqua" })
  hi("purescriptOperator", { link = "GruvboxBlue" })
  hi("purescriptTypeVar", { link = "GruvboxFg1" })
  hi("purescriptConstructor", { link = "GruvboxFg1" })
  hi("purescriptFunction", { link = "GruvboxFg1" })
  hi("purescriptConditional", { link = "GruvboxOrange" })
  hi("purescriptBacktick", { link = "GruvboxOrange" })
  hi("coffeeExtendedOp", { link = "GruvboxFg3" })
  hi("coffeeSpecialOp", { link = "GruvboxFg3" })
  hi("coffeeCurly", { link = "GruvboxOrange" })
  hi("coffeeParen", { link = "GruvboxFg3" })
  hi("coffeeBracket", { link = "GruvboxOrange" })
  hi("rubyStringDelimiter", { link = "GruvboxGreen" })
  hi("rubyInterpolationDelimiter", { link = "GruvboxAqua" })
  hi("rubyDefinedOperator", { link = "rubyKeyword" })
  hi("objcTypeModifier", { link = "GruvboxRed" })
  hi("objcDirective", { link = "GruvboxBlue" })
  hi("goDirective", { link = "GruvboxAqua" })
  hi("goConstants", { link = "GruvboxPurple" })
  hi("goDeclaration", { link = "GruvboxRed" })
  hi("goDeclType", { link = "GruvboxBlue" })
  hi("goBuiltins", { link = "GruvboxOrange" })
  hi("luaIn", { link = "GruvboxRed" })
  hi("luaFunction", { link = "GruvboxAqua" })
  hi("luaTable", { link = "GruvboxOrange" })
  hi("moonSpecialOp", { link = "GruvboxFg3" })
  hi("moonExtendedOp", { link = "GruvboxFg3" })
  hi("moonFunction", { link = "GruvboxFg3" })
  hi("moonObject", { link = "GruvboxYellow" })
  hi("javaAnnotation", { link = "GruvboxBlue" })
  hi("javaDocTags", { link = "GruvboxAqua" })
  hi("javaCommentTitle", { link = "vimCommentTitle" })
  hi("javaParen", { link = "GruvboxFg3" })
  hi("javaParen1", { link = "GruvboxFg3" })
  hi("javaParen2", { link = "GruvboxFg3" })
  hi("javaParen3", { link = "GruvboxFg3" })
  hi("javaParen4", { link = "GruvboxFg3" })
  hi("javaParen5", { link = "GruvboxFg3" })
  hi("javaOperator", { link = "GruvboxOrange" })
  hi("javaVarArg", { link = "GruvboxGreen" })
  hi("elixirDocString", { link = "Comment" })
  hi("elixirStringDelimiter", { link = "GruvboxGreen" })
  hi("elixirInterpolationDelimiter", { link = "GruvboxAqua" })
  hi("elixirModuleDeclaration", { link = "GruvboxYellow" })
  hi("scalaNameDefinition", { link = "GruvboxFg1" })
  hi("scalaCaseFollowing", { link = "GruvboxFg1" })
  hi("scalaCapitalWord", { link = "GruvboxFg1" })
  hi("scalaTypeExtension", { link = "GruvboxFg1" })
  hi("scalaKeyword", { link = "GruvboxRed" })
  hi("scalaKeywordModifier", { link = "GruvboxRed" })
  hi("scalaSpecial", { link = "GruvboxAqua" })
  hi("scalaOperator", { link = "GruvboxFg1" })
  hi("scalaTypeDeclaration", { link = "GruvboxYellow" })
  hi("scalaTypeTypePostDeclaration", { link = "GruvboxYellow" })
  hi("scalaInstanceDeclaration", { link = "GruvboxFg1" })
  hi("scalaInterpolation", { link = "GruvboxAqua" })
  hi("markdownItalic", { link = "GruvboxFg3" })
  hi("markdownBold", { link = "GruvboxFg3" })
  hi("markdownBoldItalic", { link = "GruvboxFg3" })
  hi("markdownH1", { link = "GruvboxGreen" })
  hi("markdownH2", { link = "GruvboxGreen" })
  hi("markdownH3", { link = "GruvboxYellow" })
  hi("markdownH4", { link = "GruvboxYellow" })
  hi("markdownH5", { link = "GruvboxYellow" })
  hi("markdownH6", { link = "GruvboxYellow" })
  hi("markdownCode", { link = "GruvboxAqua" })
  hi("markdownCodeBlock", { link = "GruvboxAqua" })
  hi("markdownCodeDelimiter", { link = "GruvboxAqua" })
  hi("markdownBlockquote", { link = "GruvboxGray" })
  hi("markdownListMarker", { link = "GruvboxGray" })
  hi("markdownOrderedListMarker", { link = "GruvboxGray" })
  hi("markdownRule", { link = "GruvboxGray" })
  hi("markdownHeadingRule", { link = "GruvboxGray" })
  hi("markdownUrlDelimiter", { link = "GruvboxFg3" })
  hi("markdownLinkDelimiter", { link = "GruvboxFg3" })
  hi("markdownLinkTextDelimiter", { link = "GruvboxFg3" })
  hi("markdownHeadingDelimiter", { link = "GruvboxOrange" })
  hi("markdownUrl", { link = "GruvboxPurple" })
  hi("markdownUrlTitleDelimiter", { link = "GruvboxGreen" })
  hi("markdownLinkText", { link = "GruvboxGray" })
  hi("markdownIdDeclaration", { link = "markdownLinkText" })
  hi("haskellType", { link = "GruvboxBlue" })
  hi("haskellIdentifier", { link = "GruvboxAqua" })
  hi("haskellSeparator", { link = "GruvboxFg4" })
  hi("haskellDelimiter", { link = "GruvboxOrange" })
  hi("haskellOperators", { link = "GruvboxPurple" })
  hi("haskellBacktick", { link = "GruvboxOrange" })
  hi("haskellStatement", { link = "GruvboxPurple" })
  hi("haskellConditional", { link = "GruvboxPurple" })
  hi("haskellLet", { link = "GruvboxRed" })
  hi("haskellDefault", { link = "GruvboxRed" })
  hi("haskellWhere", { link = "GruvboxRed" })
  hi("haskellBottom", { link = "GruvboxRed" })
  hi("haskellImportKeywords", { link = "GruvboxPurple" })
  hi("haskellDeclKeyword", { link = "GruvboxOrange" })
  hi("haskellDecl", { link = "GruvboxOrange" })
  hi("haskellDeriving", { link = "GruvboxPurple" })
  hi("haskellAssocType", { link = "GruvboxAqua" })
  hi("haskellNumber", { link = "GruvboxAqua" })
  hi("haskellPragma", { link = "GruvboxRed" })
  hi("haskellTH", { link = "GruvboxAqua" })
  hi("haskellForeignKeywords", { link = "GruvboxGreen" })
  hi("haskellKeyword", { link = "GruvboxRed" })
  hi("haskellFloat", { link = "GruvboxAqua" })
  hi("haskellInfix", { link = "GruvboxPurple" })
  hi("haskellQuote", { link = "GruvboxGreen" })
  hi("haskellShebang", { link = "GruvboxYellow" })
  hi("haskellLiquid", { link = "GruvboxPurple" })
  hi("haskellQuasiQuoted", { link = "GruvboxBlue" })
  hi("haskellRecursiveDo", { link = "GruvboxPurple" })
  hi("haskellQuotedType", { link = "GruvboxRed" })
  hi("haskellPreProc", { link = "GruvboxFg4" })
  hi("haskellTypeRoles", { link = "GruvboxRed" })
  hi("haskellTypeForall", { link = "GruvboxRed" })
  hi("haskellPatternKeyword", { link = "GruvboxBlue" })
  hi("jsonKeyword", { link = "GruvboxGreen" })
  hi("jsonQuote", { link = "GruvboxGreen" })
  hi("jsonBraces", { link = "GruvboxFg1" })
  hi("jsonString", { link = "GruvboxFg1" })
  hi("mailQuoted1", { link = "GruvboxAqua" })
  hi("mailQuoted2", { link = "GruvboxPurple" })
  hi("mailQuoted3", { link = "GruvboxYellow" })
  hi("mailQuoted4", { link = "GruvboxGreen" })
  hi("mailQuoted5", { link = "GruvboxRed" })
  hi("mailQuoted6", { link = "GruvboxOrange" })
  hi("mailSignature", { link = "Comment" })
  hi("csBraces", { link = "GruvboxFg1" })
  hi("csEndColon", { link = "GruvboxFg1" })
  hi("csLogicSymbols", { link = "GruvboxFg1" })
  hi("csParens", { link = "GruvboxFg3" })
  hi("csOpSymbols", { link = "GruvboxFg3" })
  hi("csInterpolationDelimiter", { link = "GruvboxFg3" })
  hi("csInterpolationAlignDel", { link = "GruvboxAqua" })
  hi("csInterpolationFormat", { link = "GruvboxAqua" })
  hi("csInterpolationFormatDel", { link = "GruvboxAqua" })
  hi("rustSigil", { link = "GruvboxOrange" })
  hi("rustEscape", { link = "GruvboxAqua" })
  hi("rustStringContinuation", { link = "GruvboxAqua" })
  hi("rustEnum", { link = "GruvboxAqua" })
  hi("rustStructure", { link = "GruvboxAqua" })
  hi("rustModPathSep", { link = "GruvboxFg2" })
  hi("rustCommentLineDoc", { link = "Comment" })
  hi("rustDefault", { link = "GruvboxAqua" })
  hi("ocamlOperator", { link = "GruvboxFg1" })
  hi("ocamlKeyChar", { link = "GruvboxOrange" })
  hi("ocamlArrow", { link = "GruvboxOrange" })
  hi("ocamlInfixOpKeyword", { link = "GruvboxRed" })
  hi("ocamlConstructor", { link = "GruvboxOrange" })

  -- treesitter
  hi("@comment", { link = "Comment" })
  hi("@none", { bg = "NONE", fg = "NONE" })
  hi("@preproc", { link = "PreProc" })
  hi("@define", { link = "Define" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation.delimiter", { link = "Delimiter" })
  hi("@punctuation.bracket", { link = "Delimiter" })
  hi("@punctuation.special", { link = "Delimiter" })
  hi("@string", { link = "String" })
  hi("@string.regex", { link = "String" })
  hi("@string.regexp", { link = "String" })
  hi("@string.escape", { link = "SpecialChar" })
  hi("@string.special", { link = "SpecialChar" })
  hi("@string.special.path", { link = "Underlined" })
  hi("@string.special.symbol", { link = "Identifier" })
  hi("@string.special.url", { link = "Underlined" })
  hi("@character", { link = "Character" })
  hi("@character.special", { link = "SpecialChar" })
  hi("@boolean", { link = "Boolean" })
  hi("@number", { link = "Number" })
  hi("@number.float", { link = "Float" })
  hi("@float", { link = "Float" })
  hi("@function", { link = "Function" })
  hi("@function.builtin", { link = "Special" })
  hi("@function.call", { link = "Function" })
  hi("@function.macro", { link = "Macro" })
  hi("@function.method", { link = "Function" })
  hi("@method", { link = "Function" })
  hi("@method.call", { link = "Function" })
  hi("@constructor", { link = "Special" })
  hi("@parameter", { link = "Identifier" })
  hi("@keyword", { link = "Keyword" })
  hi("@keyword.conditional", { link = "Conditional" })
  hi("@keyword.debug", { link = "Debug" })
  hi("@keyword.directive", { link = "PreProc" })
  hi("@keyword.directive.define", { link = "Define" })
  hi("@keyword.exception", { link = "Exception" })
  hi("@keyword.function", { link = "Keyword" })
  hi("@keyword.import", { link = "Include" })
  hi("@keyword.operator", { link = "GruvboxRed" })
  hi("@keyword.repeat", { link = "Repeat" })
  hi("@keyword.return", { link = "Keyword" })
  hi("@keyword.storage", { link = "StorageClass" })
  hi("@conditional", { link = "Conditional" })
  hi("@repeat", { link = "Repeat" })
  hi("@debug", { link = "Debug" })
  hi("@label", { link = "Label" })
  hi("@include", { link = "Include" })
  hi("@exception", { link = "Exception" })
  hi("@type", { link = "Type" })
  hi("@type.builtin", { link = "Type" })
  hi("@type.definition", { link = "Typedef" })
  hi("@type.qualifier", { link = "Type" })
  hi("@storageclass", { link = "StorageClass" })
  hi("@attribute", { link = "PreProc" })
  hi("@field", { link = "Identifier" })
  hi("@property", { link = "Identifier" })
  hi("@variable", { link = "GruvboxFg1" })
  hi("@variable.builtin", { link = "Special" })
  hi("@variable.member", { link = "Identifier" })
  hi("@variable.parameter", { link = "Identifier" })
  hi("@constant", { link = "Constant" })
  hi("@constant.builtin", { link = "Special" })
  hi("@constant.macro", { link = "Define" })
  hi("@markup", { link = "GruvboxFg1" })
  hi("@markup.strong", {})
  hi("@markup.italic", { link = "@text.emphasis" })
  hi("@markup.underline", {})
  hi("@markup.strikethrough", {})
  hi("@markup.heading", { link = "Title" })
  hi("@markup.raw", { link = "String" })
  hi("@markup.math", { link = "Special" })
  hi("@markup.environment", { link = "Macro" })
  hi("@markup.environment.name", { link = "Type" })
  hi("@markup.link", { link = "Underlined" })
  hi("@markup.link.label", { link = "SpecialChar" })
  hi("@markup.list", { link = "Delimiter" })
  hi("@markup.list.checked", { link = "GruvboxGreen" })
  hi("@markup.list.unchecked", { link = "GruvboxGray" })
  hi("@comment.todo", { link = "Todo" })
  hi("@comment.note", { link = "SpecialComment" })
  hi("@comment.warning", { link = "WarningMsg" })
  hi("@comment.error", { link = "ErrorMsg" })
  hi("@diff.plus", { link = "diffAdded" })
  hi("@diff.minus", { link = "diffRemoved" })
  hi("@diff.delta", { link = "diffChanged" })
  hi("@module", { link = "GruvboxFg1" })
  hi("@namespace", { link = "GruvboxFg1" })
  hi("@symbol", { link = "Identifier" })
  hi("@text", { link = "GruvboxFg1" })
  hi("@text.strong", {})
  hi("@text.emphasis", {})
  hi("@text.underline", {})
  hi("@text.strike", {})
  hi("@text.title", { link = "Title" })
  hi("@text.literal", { link = "String" })
  hi("@text.uri", { link = "Underlined" })
  hi("@text.math", { link = "Special" })
  hi("@text.environment", { link = "Macro" })
  hi("@text.environment.name", { link = "Type" })
  hi("@text.reference", { link = "Constant" })
  hi("@text.todo", { link = "Todo" })
  hi("@text.todo.checked", { link = "GruvboxGreen" })
  hi("@text.todo.unchecked", { link = "GruvboxGray" })
  hi("@text.note", { link = "SpecialComment" })
  hi("@text.note.comment", { fg = colors.purple })
  hi("@text.warning", { link = "WarningMsg" })
  hi("@text.danger", { link = "ErrorMsg" })
  hi("@text.danger.comment", { fg = colors.fg0, bg = colors.red })
  hi("@text.diff.add", { link = "diffAdded" })
  hi("@text.diff.delete", { link = "diffRemoved" })
  hi("@tag", { link = "Tag" })
  hi("@tag.attribute", { link = "Identifier" })
  hi("@tag.delimiter", { link = "Delimiter" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@macro", { link = "Macro" })
  hi("@structure", { link = "Structure" })
  hi("@lsp.type.class", { link = "@type" })
  hi("@lsp.type.comment", { link = "@comment" })
  hi("@lsp.type.decorator", { link = "@macro" })
  hi("@lsp.type.enum", { link = "@type" })
  hi("@lsp.type.enumMember", { link = "@constant" })
  hi("@lsp.type.function", { link = "@function" })
  hi("@lsp.type.interface", { link = "@constructor" })
  hi("@lsp.type.macro", { link = "@macro" })
  hi("@lsp.type.method", { link = "@method" })
  hi("@lsp.type.modifier.java", { link = "@keyword.type.java" })
  hi("@lsp.type.namespace", { link = "@namespace" })
  hi("@lsp.type.parameter", { link = "@parameter" })
  hi("@lsp.type.property", { link = "@property" })
  hi("@lsp.type.struct", { link = "@type" })
  hi("@lsp.type.type", { link = "@type" })
  hi("@lsp.type.typeParameter", { link = "@type.definition" })
  hi("@lsp.type.variable", { link = "@variable" })

  -- gitcommit
  hi("gitcommitBranch", { link = "GruvboxFg1" })
  hi("gitcommitComment", { link = "Comment" })
  hi("gitcommitDiscarded", { link = "Comment" })
  hi("gitcommitDiscardedFile", { link = "GruvboxRed" })
  hi("gitcommitDiscardedType", { link = "GruvboxAqua" })
  hi("gitcommitHeader", { link = "GruvboxPurple" })
  hi("gitcommitOverflow", { link = "GruvboxFg1" })
  hi("gitcommitSelected", { link = "Comment" })
  hi("gitcommitSelectedFile", { link = "GruvboxGreen" })
  hi("gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi("gitcommitSummary", { link = "GruvboxGreen" })
  hi("gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi("gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi("gitcommitUntracked", { link = "Comment" })
  hi("gitcommitUntrackedFile", { link = "GruvboxAqua" })

  -- patch diff
  hi("diffAdded", { link = "DiffAdd" })
  hi("diffRemoved", { link = "DiffDelete" })
  hi("diffChanged", { link = "DiffChange" })
  hi("diffFile", { link = "GruvboxOrange" })
  hi("diffNewFile", { link = "GruvboxYellow" })
  hi("diffOldFile", { link = "GruvboxOrange" })
  hi("diffLine", { link = "GruvboxBlue" })
  hi("diffIndexLine", { link = "diffChanged" })
  hi("Added", { link = "GruvboxGreen" })
  hi("Changed", { link = "GruvboxOrange" })
  hi("Removed", { link = "GruvboxRed" })

  -- lewis6991/gitsigns.nvim
  hi("GitSignsAdd", { link = "GruvboxGreen" })
  hi("GitSignsChange", { link = "GruvboxOrange" })
  hi("GitSignsDelete", { link = "GruvboxRed" })

  -- netrw
  hi("netrwDir", { link = "GruvboxAqua" })
  hi("netrwClassify", { link = "GruvboxAqua" })
  hi("netrwLink", { link = "GruvboxGray" })
  hi("netrwSymLink", { link = "GruvboxFg1" })
  hi("netrwExe", { link = "GruvboxYellow" })
  hi("netrwComment", { link = "GruvboxGray" })
  hi("netrwList", { link = "GruvboxBlue" })
  hi("netrwHelpCmd", { link = "GruvboxAqua" })
  hi("netrwCmdSep", { link = "GruvboxFg3" })
  hi("netrwVersion", { link = "GruvboxGreen" })

  -- hrsh7th/nvim-cmp
  hi("CmpItemAbbr", { link = "GruvboxFg0" })
  hi("CmpItemAbbrDeprecated", { link = "GruvboxFg1" })
  hi("CmpItemAbbrMatch", { link = "GruvboxBlue" })
  hi("CmpItemAbbrMatchFuzzy", { link = "GruvboxBlue" })
  hi("CmpItemMenu", { link = "GruvboxGray" })
  hi("CmpItemKindText", { link = "GruvboxOrange" })
  hi("CmpItemKindVariable", { link = "GruvboxOrange" })
  hi("CmpItemKindMethod", { link = "GruvboxBlue" })
  hi("CmpItemKindFunction", { link = "GruvboxBlue" })
  hi("CmpItemKindConstructor", { link = "GruvboxYellow" })
  hi("CmpItemKindUnit", { link = "GruvboxBlue" })
  hi("CmpItemKindField", { link = "GruvboxBlue" })
  hi("CmpItemKindClass", { link = "GruvboxYellow" })
  hi("CmpItemKindInterface", { link = "GruvboxYellow" })
  hi("CmpItemKindModule", { link = "GruvboxBlue" })
  hi("CmpItemKindProperty", { link = "GruvboxBlue" })
  hi("CmpItemKindValue", { link = "GruvboxOrange" })
  hi("CmpItemKindEnum", { link = "GruvboxYellow" })
  hi("CmpItemKindOperator", { link = "GruvboxYellow" })
  hi("CmpItemKindKeyword", { link = "GruvboxPurple" })
  hi("CmpItemKindEvent", { link = "GruvboxPurple" })
  hi("CmpItemKindReference", { link = "GruvboxPurple" })
  hi("CmpItemKindColor", { link = "GruvboxPurple" })
  hi("CmpItemKindSnippet", { link = "GruvboxGreen" })
  hi("CmpItemKindFile", { link = "GruvboxBlue" })
  hi("CmpItemKindFolder", { link = "GruvboxBlue" })
  hi("CmpItemKindEnumMember", { link = "GruvboxAqua" })
  hi("CmpItemKindConstant", { link = "GruvboxOrange" })
  hi("CmpItemKindStruct", { link = "GruvboxYellow" })
  hi("CmpItemKindTypeParameter", { link = "GruvboxYellow" })
  hi("CmpItemKindTextIcon", { link = "CmpItemKindText" })
  hi("CmpItemKindVariableIcon", { link = "CmpItemKindVariable" })
  hi("CmpItemKindMethodIcon", { link = "CmpItemKindMethod" })
  hi("CmpItemKindFunctionIcon", { link = "CmpItemKindFunction" })
  hi("CmpItemKindConstructorIcon", { link = "CmpItemKindConstructor" })
  hi("CmpItemKindUnitIcon", { link = "CmpItemKindUnit" })
  hi("CmpItemKindFieldIcon", { link = "CmpItemKindField" })
  hi("CmpItemKindClassIcon", { link = "CmpItemKindClass" })
  hi("CmpItemKindInterfaceIcon", { link = "CmpItemKindInterface" })
  hi("CmpItemKindModuleIcon", { link = "CmpItemKindModule" })
  hi("CmpItemKindPropertyIcon", { link = "CmpItemKindProperty" })
  hi("CmpItemKindValueIcon", { link = "CmpItemKindValue" })
  hi("CmpItemKindEnumIcon", { link = "CmpItemKindEnum" })
  hi("CmpItemKindOperatorIcon", { link = "CmpItemKindOperator" })
  hi("CmpItemKindKeywordIcon", { link = "CmpItemKindKeyword" })
  hi("CmpItemKindEventIcon", { link = "CmpItemKindEvent" })
  hi("CmpItemKindReferenceIcon", { link = "CmpItemKindReference" })
  hi("CmpItemKindColorIcon", { link = "CmpItemKindColor" })
  hi("CmpItemKindSnippetIcon", { link = "CmpItemKindSnippet" })
  hi("CmpItemKindFileIcon", { link = "CmpItemKindFile" })
  hi("CmpItemKindFolderIcon", { link = "CmpItemKindFolder" })
  hi("CmpItemKindEnumMemberIcon", { link = "CmpItemKindEnumMember" })
  hi("CmpItemKindConstantIcon", { link = "CmpItemKindConstant" })
  hi("CmpItemKindStructIcon", { link = "CmpItemKindStruct" })
  hi("CmpItemKindTypeParameterIcon", { link = "CmpItemKindTypeParameter" })
  hi("CmpCursorLine", { fg = colors.bg0, bg = colors.blue })

  -- mfussenegger/nvim-dap
  hi("DapBreakpointSymbol", { fg = colors.red, bg = colors.bg1 })
  hi("DapStoppedSymbol", { fg = colors.green, bg = colors.bg1 })

  -- rcarriga/nvim-dap-ui
  hi("DapUIBreakpointsCurrentLine", { link = "GruvboxYellow" })
  hi("DapUIBreakpointsDisabledLine", { link = "GruvboxGray" })
  hi("DapUIBreakpointsInfo", { link = "GruvboxAqua" })
  hi("DapUIBreakpointsLine", { link = "GruvboxYellow" })
  hi("DapUIBreakpointsPath", { link = "GruvboxBlue" })
  hi("DapUICurrentFrameName", { link = "GruvboxPurple" })
  hi("DapUIDecoration", { link = "GruvboxPurple" })
  hi("DapUIEndofBuffer", { link = "EndOfBuffer" })
  hi("DapUIFloatBorder", { link = "GruvboxAqua" })
  hi("DapUILineNumber", { link = "GruvboxYellow" })
  hi("DapUIModifiedValue", { link = "GruvboxRed" })
  hi("DapUIPlayPause", { link = "GruvboxGreen" })
  hi("DapUIRestart", { link = "GruvboxGreen" })
  hi("DapUIScope", { link = "GruvboxBlue" })
  hi("DapUISource", { link = "GruvboxFg1" })
  hi("DapUIStepBack", { link = "GruvboxBlue" })
  hi("DapUIStepInto", { link = "GruvboxBlue" })
  hi("DapUIStepOut", { link = "GruvboxBlue" })
  hi("DapUIStepOver", { link = "GruvboxBlue" })
  hi("DapUIStop", { link = "GruvboxRed" })
  hi("DapUIStoppedThread", { link = "GruvboxBlue" })
  hi("DapUIThread", { link = "GruvboxBlue" })
  hi("DapUIType", { link = "GruvboxOrange" })
  hi("DapUIUnavailable", { link = "GruvboxGray" })
  hi("DapUIWatchesEmpty", { link = "GruvboxGray" })
  hi("DapUIWatchesError", { link = "GruvboxRed" })
  hi("DapUIWatchesValue", { link = "GruvboxYellow" })
  hi("DapUIWinSelect", { link = "GruvboxYellow" })

  -- nvim-mini/mini.nvim
  hi("MiniHipatternsFixme", { fg = colors.bg0, bg = colors.red })
  hi("MiniHipatternsHack", { fg = colors.bg0, bg = colors.yellow })
  hi("MiniHipatternsNote", { fg = colors.bg0, bg = colors.blue })
  hi("MiniHipatternsTodo", { fg = colors.bg0, bg = colors.aqua })
  hi("MiniIconsAzure", { link = "GruvboxBlue" })
  hi("MiniIconsBlue", { link = "GruvboxBlue" })
  hi("MiniIconsCyan", { link = "GruvboxAqua" })
  hi("MiniIconsGreen", { link = "GruvboxGreen" })
  hi("MiniIconsGrey", { link = "GruvboxFg0" })
  hi("MiniIconsOrange", { link = "GruvboxOrange" })
  hi("MiniIconsPurple", { link = "GruvboxPurple" })
  hi("MiniIconsRed", { link = "GruvboxRed" })
  hi("MiniIconsYellow", { link = "GruvboxYellow" })
  hi("MiniIndentscopeSymbol", { link = "GruvboxGray" })
  hi("MiniIndentscopeSymbolOff", { link = "GruvboxYellow" })
  hi("MiniJump", { link = "GruvboxAqua" })
  hi("MiniJump2dDim", { link = "GruvboxGray" })
  hi("MiniJump2dSpot", { fg = colors.bg0, bg = colors.aqua, nocombine = true })
  hi("MiniJump2dSpotAhead", { link = "MiniJump2dSpot" })
  hi("MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi("MiniNotifyBorder", { link = "FloatBorder" })
  hi("MiniNotifyNormal", { link = "NormalFloat" })
  hi("MiniNotifyTitle", { link = "FloatTitle" })
  hi("MiniPickBorder", { link = "FloatBorder" })
  hi("MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
  hi("MiniPickBorderText", { link = "FloatTitle" })
  hi("MiniPickIconDirectory", { link = "Directory" })
  hi("MiniPickIconFile", { link = "MiniPickNormal" })
  hi("MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi("MiniPickMatchCurrent", { bg = colors.bg2 })
  hi("MiniPickMatchMarked", { link = "Visual" })
  hi("MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi("MiniPickNormal", { link = "NormalFloat" })
  hi("MiniPickPreviewLine", { link = "CursorLine" })
  hi("MiniPickPreviewRegion", { link = "IncSearch" })
  hi("MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
  hi("MiniStarterCurrent", { nocombine = true })
  hi("MiniStarterFooter", { link = "GruvboxGray" })
  hi("MiniStarterHeader", { link = "Title" })
  hi("MiniStarterInactive", { link = "Comment" })
  hi("MiniStarterItem", { link = "Normal" })
  hi("MiniStarterItemBullet", { link = "Delimiter" })
  hi("MiniStarterItemPrefix", { link = "WarningMsg" })
  hi("MiniStarterSection", { link = "Delimiter" })
  hi("MiniStarterQuery", { link = "MoreMsg" })
  hi("MiniStatuslineInactive", { link = "StatusLineNC" })
  hi("MiniStatuslineSectionB", { link = "StatusLine" })
  hi("MiniStatuslineSectionC", { link = "StatusLineNC" })
  hi("MiniStatuslineModeCommand", { fg = colors.bg0, bg = colors.purple })
  hi("MiniStatuslineModeInsert", { fg = colors.bg0, bg = colors.green })
  hi("MiniStatuslineModeNormal", { fg = colors.bg0, bg = colors.fg1 })
  hi("MiniStatuslineModeOther", { fg = colors.bg0, bg = colors.aqua })
  hi("MiniStatuslineModeReplace", { fg = colors.bg0, bg = colors.yellow })
  hi("MiniStatuslineModeVisual", { fg = colors.bg0, bg = colors.red })
  hi("MiniSurround", { link = "IncSearch" })
  hi("MiniTablineCurrent", { fg = colors.green, bg = colors.bg0 })
  hi("MiniTablineFill", { link = "TabLineFill" })
  hi("MiniTablineHidden", { fg = colors.bg4, bg = nil })
  hi("MiniTablineModifiedCurrent", { fg = colors.bg1, bg = colors.green })
  hi("MiniTablineModifiedHidden", { fg = colors.bg1, bg = colors.bg4 })
  hi("MiniTablineModifiedVisible", { fg = colors.bg1, bg = colors.fg1 })
  hi("MiniTablineTabpagesection", { link = "Search" })
  hi("MiniTablineVisible", { fg = colors.fg1, bg = colors.bg0 })

  -- nvim-treesitter/nvim-treesitter-context
  hi("TreesitterContext", { link = "NormalFloat" })
  hi("TreesitterContextBottom", { fg = nil })
  hi("TreesitterContextLineNumber", { link = "LineNr" })
  hi("TreesitterContextLineNumberBottom", { link = "WinSeparator" })
  hi("TreesitterContextSeparator", { link = "WinSeparator" })
end


setup()
