general {
  lock_cmd = hyprlock
}


# lockscreen
listener {
  timeout = 150
  on-timeout = hyprlock
}


# turn off screen
listener {
  timeout = 450
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}


# suspend
listener {
  timeout = 900
  on-timeout = systemctl suspend
}
