source = ~/.config/hypr/theme.conf


general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = false
  fractional_scaling = 2
  fail_timeout = 2000
}


background {
  monitor =
  path = ~/.config/hypr/wallpapers/1.png
  color = $mantle

  blur_size = 3
  blur_passes = 3
  noise = 0
  contrast = 1.3
  brightness = 0.6
  vibrancy = 0.2
  vibrancy_darkness = 0
}


label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +%H)"
  color = $text
  font_size = 150
  font_family = JetBrains Mono Black

  halign = center
  valign = center
  position = 0, 250
}


label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +%M)"
  color = $text
  font_size = 150
  font_family = JetBrains Mono Black

  halign = center
  valign = center
  position = 0, 50
}


input-field {
  monitor =
  size = 250, 60
  rounding = 30
  outline_thickness = 4

  dots_size = 0.25
  dots_spacing = 0.65
  dots_center = true
  dots_rouding = -1

  font_color = $text
  inner_color = $base
  outer_color = $blue
  check_color = $green
  fail_color = $red

  placeholder_text =
  fail_text =
  fade_on_empty = false

  halign = center
  valign = center
  position = 0, -200
}


label {
  monitor =
  text = Hey there, $USER!
  color = $text
  font_size = 20
  font_family = JetBrains Mono Bold

  halign = center
  valign = bottom
  position = 0, 50
}
