# source theme
source = ~/.config/hypr/theme.conf


# general
general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = false
  fractional_scaling = 2
  fail_timeout = 2000
}


# background
background {
  monitor =
  path = ~/.config/hypr/wallpapers/1.png
  color = $base

  blur_size = 5
  blur_passes = 2
  noise = 0
  contrast = 1.3
  brightness = 0.6
  vibrancy = 0.21
  vibrancy_darkness = 0
}


# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%d %B %Y")"
  color = $text
  font_size = 22
  font_family = JetBrains Mono Bold

  halign = center
  valign = center
  position = 0, 300
}


# time
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 140
  font_family = JetBrains Mono Bold

  halign = center
  valign = center
  position = 0, 150
}


# greeting
label {
  monitor =
  text = welcome, $USER
  color = $text
  font_size = 18
  font_family = JetBrains Mono Bold

  halign = center
  valign = bottom
  position = 0, 350
}


# input
input-field {
  monitor =
  size = 300, 50
  rounding = 10
  outline_thickness = 3

  dots_size = 0.25
  dots_spacing = 0.65
  dots_center = true
  dots_rouding = -1
  font_color = $text

  inner_color = $base
  outer_color = $blue
  check_color = $green
  fail_color = $red

  placeholder_text =
  fail_text =
  fade_on_empty = false

  halign = center
  valign = bottom
  position = 0, 275
}


# song
label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/hypr/scripts/song.sh)"
  color = $blue
  font_size = 18
  font_family = JetBrains Mono NF Bold

  halign = center
  valign = bottom
  position = 0, 50
}
