# source theme
source = ~/.config/hypr/theme.conf


# general
general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = false
  fractional_scaling = 2
  fail_timeout = 2000
}


# background
background {
  monitor =
  path = ~/.config/hypr/wallpapers/4.jpg
  color = $base

  blur_size = 3
  blur_passes = 3
  noise = 0
  contrast = 1.3
  brightness = 0.6
  vibrancy = 0.2
  vibrancy_darkness = 0
}


# time
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 135
  font_family = JetBrains Mono Bold

  halign = center
  valign = center
  position = 0, 225
}


# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
  color = $text
  font_size = 30
  font_family = JetBrains Mono Bold

  halign = center
  valign = center
  position = 0, 100
}


# greeting
label {
  monitor =
  text = Hi, $USER
  color = $text
  font_size = 20
  font_family = JetBrains Mono Bold Italic

  halign = center
  valign = center
  position = 0, -125
}


# input
input-field {
  monitor =
  size = 250, 55
  rounding = 25
  outline_thickness = 3
  font_family = JetBrains Mono Bold Italic

  dots_size = 0.25
  dots_spacing = 0.65
  dots_center = true
  dots_rouding = -1

  font_color = $text
  inner_color = $base
  outer_color = $blue
  check_color = $green
  fail_color = $red

  placeholder_text = Enter Pass
  fail_text =
  fade_on_empty = false

  halign = center
  valign = center
  position = 0, -200
}


# song
label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/hypr/scripts/song.sh)"
  color = $text
  font_size = 20
  font_family = JetBrains Mono NF Bold

  halign = center
  valign = bottom
  position = 0, 50
}
