exec-once = gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-blue-standard+default"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
exec-once = gsettings set org.gnome.desktop.interface font-name "JetBrains Mono Medium 12"

exec-once = awww-daemon
exec-once = hypridle
exec-once = waybar
exec-once = mako
