$mainMod = SUPER


# general
bind = $mainMod,     RETURN, exec,           ghostty
bind = $mainMod,     D,      exec,           rofi -show drun
bind = $mainMod,     C,      killactive,
bind = $mainMod,     F,      togglefloating,
bind = $mainMod,     S,      fullscreen,
bind = $mainMod ALT, R,      exec,           hyprctl reload
bind = $mainMod,     V,      exec,           ~/.config/hypr/scripts/layouts.sh
bind = $mainMod ALT, W,      exec,           ~/.config/hypr/scripts/wallpaper.sh
bind = $mainMod ALT, B,      exec,           pkill -SIGUSR1 waybar


# launch software
bind = $mainMod ALT,  F, exec, ghostty -e yazi
bind = $mainMod ALT,  M, exec, hyprlock
bind = $mainMod CTRL, C, exec, hyprpicker -a
bind = $mainMod CTRL, F, exec, grim ~/Pictures/$(date +"%H:%M_%d-%m-%y").png
bind = $mainMod CTRL, S, exec, grim -g "$(slurp -b 11111b80 -c cdd6f4ff -w 0)" ~/Pictures/$(date +"%H:%M_%d-%m-%y").png
bind = $mainMod,      W, exec, ~/.config/hypr/scripts/wifi.sh
bind = $mainMod,      G, exec, ~/.config/hypr/scripts/search.sh
bind = $mainMod,      B, exec, ~/.config/hypr/scripts/bluetooth.sh
bind = $mainMod,      X, exec, wlogout -b 4


# move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r


# move windows
bind = $mainMod ALT, H, movewindow, l
bind = $mainMod ALT, J, movewindow, d
bind = $mainMod ALT, K, movewindow, u
bind = $mainMod ALT, L, movewindow, r


# resize window
bind = $mainMod CTRL, H, resizeactive, -50 0
bind = $mainMod CTRL, J, resizeactive, 0 50
bind = $mainMod CTRL, K, resizeactive, 0 -50
bind = $mainMod CTRL, L, resizeactive, 50 0


# switch workspace
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7


# move window to workspace
bind = $mainMod ALT, 1, movetoworkspacesilent, 1
bind = $mainMod ALT, 2, movetoworkspacesilent, 2
bind = $mainMod ALT, 3, movetoworkspacesilent, 3
bind = $mainMod ALT, 4, movetoworkspacesilent, 4
bind = $mainMod ALT, 5, movetoworkspacesilent, 5
bind = $mainMod ALT, 6, movetoworkspacesilent, 6
bind = $mainMod ALT, 7, movetoworkspacesilent, 7


# volume control
bindel = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bindel = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindel = , XF86AudioMute,        exec, pactl set-sink-mute @DEFAULT_SINK toggle


# move/resize windows with LMB/RMB
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
