source = ~/.config/hypr/theme.conf


general {
  gaps_in = 10
  gaps_out = 20

  border_size = 4
  # col.active_border = rgb(e78a4e) rgb(d8a657) 45deg
  col.active_border = rgb(7daea3)
  col.inactive_border = $surface0
  resize_on_border = false

  layout = dwindle
  allow_tearing = false
}


decoration {
  rounding = 0
  rounding_power = 3

  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.2
  dim_around = 0.2

  shadow {
    enabled = false
    range = 30
    render_power = 3
    offset = 0 0
    color = rgba($mantleAlphacc)
  }

  blur {
    enabled = false
    size = 3
    passes = 2
    vibrancy = 0.17
  }
}
