source = ~/.config/hypr/theme.conf


general {
  gaps_in = 8
  gaps_out = 20

  border_size = 3
  col.active_border = $blue $green 45deg
  col.inactive_border = $surface0
  resize_on_border = false
  no_border_on_floating = false

  layout = dwindle
  allow_tearing = false
}


decoration {
  rounding = 10
  rounding_power = 5

  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.2
  dim_around = 0.2

  shadow {
    enabled = true
    range = 30
    render_power = 3
    offset = 0 0
    color = rgba($mantleAlphacc)
  }

  blur {
    enabled = true
    size = 3
    passes = 2
    vibrancy = 0.1696
  }
}
