input {
  kb_layout = us, ru
  kb_options = grp:win_space_toggle

  repeat_delay = 275
  repeat_rate = 30

  follow_mouse = 0
  sensitivity = 0
}


dwindle {
  pseudotile = true
  force_split = 2
  preserve_split = true
  default_split_ratio = 1.0
}


master {
  new_status = master
  mfact = 0.50
  new_on_top = true
  orientation = left
}


cursor {
  no_warps = true
}


ecosystem {
  enforce_permissions = 0
}


misc {
  force_default_wallpaper = -1
  disable_hyprland_logo = true
  font_family = JetBrains Mono
  animate_manual_resizes = false
  disable_autoreload = true
}
