# windows
windowrule = match:class imv, float on
windowrule = match:class imv, size 1600 900
windowrule = match:class imv, center on
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class org.pulseaudio.pavucontrol, size 630 400
windowrule = match:class org.pulseaudio.pavucontrol, move 1200 60


# workspaces
windowrule = match:class org.telegram.desktop, workspace 2
windowrule = match:class zen, workspace 3
windowrule = match:class obsidian, workspace 4
windowrule = match:class blender, workspace 5
windowrule = match:class spotify, workspace 6


# layers
layerrule = match:namespace rofi, animation slide
layerrule = match:namespace notifications, animation slide
layerrule = match:namespace logout_dialog, animation slide
