# windows
# windowrule = float, class:nemo
# windowrule = opacity 0.90, class:nemo
# windowrule = size 1000 600, class:nemo
windowrule = float, class:imv
windowrule = size 1600 900, class:imv
windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = size 630 400, class:org.pulseaudio.pavucontrol
windowrule = move 1200 60, class:org.pulseaudio.pavucontrol
windowrule = opacity 0.98, class:obsidian


# workspaces
windowrule = workspace 2, class:org.telegram.desktop
windowrule = workspace 3, class:zen
windowrule = workspace 4, class:obsidian
windowrule = workspace 5, class:blender
windowrule = workspace 6, class:spotify


# layers
layerrule = animation slide, rofi
layerrule = animation slide, notifications
layerrule = blur, logout_dialog
