require("gitsigns").setup {
  signs = {
    add = { text = "┃" },
    change = { text = "┃" },
    delete = { text = "-" },
    topdelete = { text = "-" },
    changedelete = { text = "~" },
    untracked = { text = "¦" },
  },
  signs_staged_enable = true,
  signs_staged = {
    add = { text = "┃" },
    change = { text = "┃" },
    delete = { text = "-" },
    topdelete = { text = "-" },
    changedelete = { text = "~" },
    untracked = { text = "¦" },
  },
  signcolumn = true,
  numhl = false,
  linehl = false,
  word_diff = false,
  diff_opts = {
    algorithm = "histogram",
    ignore_whitespace_change = true,
  },
  current_line_blame = false,
  current_line_blame_opts = {
    virt_text = true,
    virt_text_pos = "eol",
    delay = 100,
    ignore_whitespace = false,
  },
  current_line_blame_formatter = "<author>, <author_time:%d-%m-%y>: <summary>",
  attach_to_untracked = true,
  sign_priority = 6,
  update_debounce = 100,
  status_formatter = nil,
  max_file_length = 40000,
}
