local Colors = {}


local default = {
  palette = {
    bg_dim = "#141617",
    bg0 = "#1d2021",
    bg1 = "#3c3836",
    bg2 = "#504945",
    bg3 = "#665c54",
    bg4 = "#7c6f64",
    fg0 = "#fbf1c7",
    fg1 = "#ebdbb2",
    fg2 = "#d5c4a1",
    fg3 = "#bdae93",
    fg4 = "#a89984",
    red = "#ea6962",
    green = "#a9b665",
    yellow = "#d8a657",
    blue = "#7daea3",
    purple = "#d3869b",
    aqua = "#89b482",
    orange = "#e78a4e",
    gray = "#928374",
    dark_red = "#722529",
    dark_green = "#62693e",
    dark_aqua = "#49503b",
  },
}


local hex_to_rgb = function(hex_str)
  local hex = "[abcdef0-9][abcdef0-9]"
  local pat = "^#(" .. hex .. ")(" .. hex .. ")(" .. hex .. ")$"
	hex_str = string.lower(hex_str)

  assert(string.find(hex_str, pat) ~= nil, "hex_to_rgb: invalid hex_str: " .. tostring(hex_str))

  local red, green, blue = string.match(hex_str, pat)
	return {
    tonumber(red, 16),
    tonumber(green, 16),
    tonumber(blue, 16)
  }
end


local function blend(fg, bg, alpha)
  bg = hex_to_rgb(bg)
  fg = hex_to_rgb(fg)

  local blendChannel = function(i)
    local ret = (alpha * fg[i] + ((1 - alpha) * bg[i]))
    return math.floor(math.min(math.max(0, ret), 255) + 0.5)
  end

  return string.format("#%02X%02X%02X", blendChannel(1), blendChannel(2), blendChannel(3))
end


local function darken(hex, amount, bg)
  return blend(hex, bg or "#000000", math.abs(amount))
end


function Colors.setup(config)
  config = config or default

  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "colors"
  vim.o.termguicolors = true

  local p = vim.tbl_deep_extend("force", default.palette, config.palette or {})

  local function hi(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  vim.g.terminal_color_0 = p.bg0
  vim.g.terminal_color_1 = p.red
  vim.g.terminal_color_2 = p.green
  vim.g.terminal_color_3 = p.yellow
  vim.g.terminal_color_4 = p.blue
  vim.g.terminal_color_5 = p.purple
  vim.g.terminal_color_6 = p.aqua
  vim.g.terminal_color_7 = p.fg4
  vim.g.terminal_color_8 = p.gray
  vim.g.terminal_color_9 = p.red
  vim.g.terminal_color_10 = p.green
  vim.g.terminal_color_11 = p.yellow
  vim.g.terminal_color_12 = p.blue
  vim.g.terminal_color_13 = p.purple
  vim.g.terminal_color_14 = p.aqua
  vim.g.terminal_color_15 = p.fg1

  -- theme colors
  hi("ColorsBgDim", { fg = p.bg_dim })
  hi("ColorsBg0", { fg = p.bg0 })
  hi("ColorsBg1", { fg = p.bg1 })
  hi("ColorsBg2", { fg = p.bg2 })
  hi("ColorsBg3", { fg = p.bg3 })
  hi("ColorsBg4", { fg = p.bg4 })
  hi("ColorsFg0", { fg = p.fg0 })
  hi("ColorsFg1", { fg = p.fg1 })
  hi("ColorsFg2", { fg = p.fg2 })
  hi("ColorsFg3", { fg = p.fg3 })
  hi("ColorsFg4", { fg = p.fg4 })
  hi("ColorsRed", { fg = p.red })
  hi("ColorsGreen", { fg = p.green })
  hi("ColorsYellow", { fg = p.yellow })
  hi("ColorsBlue", { fg = p.blue })
  hi("ColorsPurple", { fg = p.purple })
  hi("ColorsAqua", { fg = p.aqua })
  hi("ColorsOrange", { fg = p.orange })
  hi("ColorsGray", { fg = p.gray })

  -- general
  hi("Normal", { fg = p.fg1, bg = p.bg0 })
  hi("NormalFloat", { fg = p.fg1, bg = p.bg0 })
  hi("NormalNC", { link = "Normal" })
  hi("CursorLine", { bg = p.bg1 })
  hi("CursorColumn", { link = "CursorLine" })
  hi("TabLineFill", { fg = p.bg4, bg = p.bg_dim })
  hi("TabLineSel", { fg = p.green, bg = nil })
  hi("TabLine", { link = "TabLineFill" })
  hi("MatchParen", { bg = p.bg3 })
  hi("ColorColumn", { bg = p.bg1 })
  hi("Conceal", { fg = p.blue })
  hi("CursorLineNr", { link = "ColorsPurple" })
  hi("NonText", { link = "ColorsBg2" })
  hi("SpecialKey", { link = "ColorsFg4" })
  hi("Visual", { bg = p.bg1 })
  hi("VisualNOS", { link = "Visual" })
  hi("Search", { fg = p.bg1, bg = p.orange })
  hi("IncSearch", { link = "Search" })
  hi("CurSearch", { link = "IncSearch" })
  hi("QuickFixLine", { link = "ColorsPurple" })
  hi("Underlined", { link = "ColorsBlue" })
  hi("StatusLine", { fg = p.fg1, bg = p.bg2 })
  hi("StatusLineNC", { fg = p.fg4, bg = p.bg1 })
  hi("WinBar", { link = "Normal" })
  hi("WinBarNC", { link = "WinBar" })
  hi("WinSeparator", { link = "ColorsBg3" })
  hi("WildMenu", { fg = p.blue, bg = p.bg2 })
  hi("Directory", { link = "ColorsGreen" })
  hi("Title", { link = "ColorsGreen" })
  hi("ErrorMsg", { fg = p.bg0, bg = p.red })
  hi("MoreMsg", { link = "ColorsYellow" })
  hi("ModeMsg", { link = "ColorsYellow" })
  hi("Question", { link = "ColorsOrange" })
  hi("WarningMsg", { link = "ColorsRed" })
  hi("LineNr", { link = "ColorsBg4" })
  hi("SignColumn", { link = "Normal" })
  hi("Folded", { fg = p.gray, bg = p.bg1 })
  hi("FoldColumn", { fg = p.gray, bg = nil })
  hi("Cursor", { reverse = true })
  hi("vCursor", { link = "Cursor" })
  hi("iCursor", { link = "Cursor" })
  hi("lCursor", { link = "Cursor" })
  hi("Special", { link = "ColorsOrange" })
  hi("Comment", { link = "ColorsGray" })
  hi("Todo", { fg = p.bg0, bg = p.yellow })
  hi("Done", { link = "ColorsOrange" })
  hi("Error", { link = "ColorsRed" })
  hi("Pmenu", { fg = p.fg1, bg = p.bg2 })
  hi("PmenuSel", { fg = p.bg2, bg = p.blue })
  hi("PmenuSbar", { bg = p.bg2 })
  hi("PmenuThumb", { bg = p.bg4 })
  hi("PmenuKind", { link = "Pmenu" })
  hi("DiffDelete", { bg = darken(p.red, 0.18, p.bg0) })
  hi("DiffAdd", { bg = darken(p.green, 0.18, p.bg0) })
  hi("DiffChange", { bg = darken(p.blue, 0.07, p.bg0) })
  hi("DiffText", { bg = darken(p.blue, 0.30, p.bg0) })
  hi("SpellCap", { link = "ColorsBlue" })
  hi("SpellBad", { link = "ColorsRed" })
  hi("SpellLocal", { link = "ColorsAqua" })
  hi("SpellRare", { link = "ColorsPurple" })
  hi("Whitespace", { link = "ColorsBg2" })
  hi("EndOfBuffer", { link = "NonText" })
  hi("Debug", { link = "Special" })

  -- syntax
  hi("Statement", { link = "ColorsRed" })
  hi("Conditional", { link = "ColorsRed" })
  hi("Repeat", { link = "ColorsRed" })
  hi("Label", { link = "ColorsRed" })
  hi("Exception", { link = "ColorsRed" })
  hi("Operator", { link = "ColorsFg2" })
  hi("Keyword", { link = "ColorsPurple" })
  hi("Identifier", { link = "ColorsBlue" })
  hi("Function", { link = "ColorsBlue" })
  hi("PreProc", { link = "ColorsAqua" })
  hi("Include", { link = "ColorsAqua" })
  hi("Define", { link = "ColorsAqua" })
  hi("Delimiter", { link = "ColorsFg2" })
  hi("Macro", { link = "ColorsPurple" })
  hi("PreCondit", { link = "ColorsAqua" })
  hi("Constant", { link = "ColorsOrange" })
  hi("Character", { link = "ColorsPurple" })
  hi("String", { link = "ColorsGreen" })
  hi("Boolean", { link = "ColorsOrange" })
  hi("Number", { link = "ColorsOrange" })
  hi("Float", { link = "Number" })
  hi("Type", { link = "ColorsYellow" })
  hi("StorageClass", { link = "ColorsOrange" })
  hi("Structure", { link = "ColorsAqua" })
  hi("Typedef", { link = "ColorsYellow" })

  -- lsp
  hi("DiagnosticError", { link = "ColorsRed" })
  hi("DiagnosticWarn", { link = "ColorsYellow" })
  hi("DiagnosticInfo", { link = "ColorsBlue" })
  hi("DiagnosticDeprecated", { strikethrough = true })
  hi("DiagnosticHint", { link = "ColorsAqua" })
  hi("DiagnosticOk", { link = "ColorsGreen" })
  hi("DiagnosticSignError", { link = "ColorsRed" })
  hi("DiagnosticSignWarn", { link = "ColorsYellow" })
  hi("DiagnosticSignInfo", { link = "ColorsBlue" })
  hi("DiagnosticSignHint", { link = "ColorsAqua" })
  hi("DiagnosticSignOk", { link = "ColorsGreen" })
  hi("DiagnosticUnderlineError", { link = "ColorsRed" })
  hi("DiagnosticUnderlineWarn", { link = "ColorsYellow" })
  hi("DiagnosticUnderlineInfo", { link = "ColorsBlue" })
  hi("DiagnosticUnderlineHint", { link = "ColorsAqua" })
  hi("DiagnosticUnderlineOk", { link = "ColorsGreen" })
  hi("DiagnosticFloatingError", { link = "ColorsRed" })
  hi("DiagnosticFloatingWarn", { link = "ColorsOrange" })
  hi("DiagnosticFloatingInfo", { link = "ColorsBlue" })
  hi("DiagnosticFloatingHint", { link = "ColorsAqua" })
  hi("DiagnosticFloatingOk", { link = "ColorsGreen" })
  hi("DiagnosticVirtualTextError", { link = "ColorsRed" })
  hi("DiagnosticVirtualTextWarn", { link = "ColorsYellow" })
  hi("DiagnosticVirtualTextInfo", { link = "ColorsBlue" })
  hi("DiagnosticVirtualTextHint", { link = "ColorsAqua" })
  hi("DiagnosticVirtualTextOk", { link = "ColorsGreen" })
  hi("LspReferenceRead", { link = "ColorsYellow" })
  hi("LspReferenceTarget", { link = "Visual" })
  hi("LspReferenceText", { link = "ColorsYellow" })
  hi("LspReferenceWrite", { link = "ColorsOrange" })
  hi("LspCodeLens", { link = "ColorsGray" })
  hi("LspSignatureActiveParameter", { link = "Search" })
  hi("LspInlayHint", { link = "Comment" })

  -- languages
  hi("htmlTag", { link = "ColorsAqua" })
  hi("htmlEndTag", { link = "ColorsAqua" })
  hi("htmlTagName", { link = "ColorsBlue" })
  hi("htmlArg", { link = "ColorsOrange" })
  hi("htmlTagN", { link = "ColorsFg1" })
  hi("htmlSpecialTagName", { link = "ColorsBlue" })
  hi("htmlLink", { link = "ColorsFg4" })
  hi("htmlSpecialChar", { link = "ColorsRed" })
  hi("htmlBold", { fg = p.fg0, bg = p.bg0 })
  hi("htmlBoldUnderline", { fg = p.fg0, bg = p.bg0 })
  hi("htmlBoldItalic", { fg = p.fg0, bg = p.bg0 })
  hi("htmlBoldUnderlineItalic", { fg = p.fg0, bg = p.bg0 })
  hi("htmlUnderline", { fg = p.fg0, bg = p.bg0 })
  hi("htmlUnderlineItalic", { fg = p.fg0, bg = p.bg0 })
  hi("htmlItalic", { fg = p.fg0, bg = p.bg0 })
  hi("xmlTag", { link = "ColorsAqua" })
  hi("xmlEndTag", { link = "ColorsAqua" })
  hi("xmlTagName", { link = "ColorsBlue" })
  hi("xmlEqual", { link = "ColorsBlue" })
  hi("docbkKeyword", { link = "ColorsAqua" })
  hi("xmlDocTypeDecl", { link = "ColorsGray" })
  hi("xmlDocTypeKeyword", { link = "ColorsPurple" })
  hi("xmlCdataStart", { link = "ColorsGray" })
  hi("xmlCdataCdata", { link = "ColorsPurple" })
  hi("dtdFunction", { link = "ColorsGray" })
  hi("dtdTagName", { link = "ColorsPurple" })
  hi("xmlAttrib", { link = "ColorsOrange" })
  hi("xmlProcessingDelim", { link = "ColorsGray" })
  hi("dtdParamEntityPunct", { link = "ColorsGray" })
  hi("dtdParamEntityDPunct", { link = "ColorsGray" })
  hi("xmlAttribPunct", { link = "ColorsGray" })
  hi("xmlEntity", { link = "ColorsRed" })
  hi("xmlEntityPunct", { link = "ColorsRed" })
  hi("clojureKeyword", { link = "ColorsBlue" })
  hi("clojureCond", { link = "ColorsOrange" })
  hi("clojureSpecial", { link = "ColorsOrange" })
  hi("clojureDefine", { link = "ColorsOrange" })
  hi("clojureFunc", { link = "ColorsYellow" })
  hi("clojureRepeat", { link = "ColorsYellow" })
  hi("clojureCharacter", { link = "ColorsAqua" })
  hi("clojureStringEscape", { link = "ColorsAqua" })
  hi("clojureException", { link = "ColorsRed" })
  hi("clojureRegexp", { link = "ColorsAqua" })
  hi("clojureRegexpEscape", { link = "ColorsAqua" })
  hi("clojureRegexpCharClass", { link = "ColorsFg3" })
  hi("clojureRegexpMod", { link = "clojureRegexpCharClass" })
  hi("clojureRegexpQuantifier", { link = "clojureRegexpCharClass" })
  hi("clojureParen", { link = "ColorsFg3" })
  hi("clojureAnonArg", { link = "ColorsYellow" })
  hi("clojureVariable", { link = "ColorsBlue" })
  hi("clojureMacro", { link = "ColorsOrange" })
  hi("clojureMeta", { link = "ColorsYellow" })
  hi("clojureDeref", { link = "ColorsYellow" })
  hi("clojureQuote", { link = "ColorsYellow" })
  hi("clojureUnquote", { link = "ColorsYellow" })
  hi("cOperator", { link = "ColorsPurple" })
  hi("cppOperator", { link = "ColorsPurple" })
  hi("cStructure", { link = "ColorsOrange" })
  hi("pythonBuiltin", { link = "ColorsOrange" })
  hi("pythonBuiltinObj", { link = "ColorsOrange" })
  hi("pythonBuiltinFunc", { link = "ColorsOrange" })
  hi("pythonFunction", { link = "ColorsAqua" })
  hi("pythonDecorator", { link = "ColorsRed" })
  hi("pythonInclude", { link = "ColorsBlue" })
  hi("pythonImport", { link = "ColorsBlue" })
  hi("pythonRun", { link = "ColorsBlue" })
  hi("pythonCoding", { link = "ColorsBlue" })
  hi("pythonOperator", { link = "ColorsRed" })
  hi("pythonException", { link = "ColorsRed" })
  hi("pythonExceptions", { link = "ColorsPurple" })
  hi("pythonBoolean", { link = "ColorsPurple" })
  hi("pythonDot", { link = "ColorsFg3" })
  hi("pythonConditional", { link = "ColorsRed" })
  hi("pythonRepeat", { link = "ColorsRed" })
  hi("pythonDottedName", { link = "ColorsGreen" })
  hi("cssBraces", { link = "ColorsBlue" })
  hi("cssFunctionName", { link = "ColorsYellow" })
  hi("cssIdentifier", { link = "ColorsOrange" })
  hi("cssClassName", { link = "ColorsGreen" })
  hi("cssColor", { link = "ColorsBlue" })
  hi("cssSelectorOp", { link = "ColorsBlue" })
  hi("cssSelectorOp2", { link = "ColorsBlue" })
  hi("cssImportant", { link = "ColorsGreen" })
  hi("cssVendor", { link = "ColorsFg1" })
  hi("cssTextProp", { link = "ColorsAqua" })
  hi("cssAnimationProp", { link = "ColorsAqua" })
  hi("cssUIProp", { link = "ColorsYellow" })
  hi("cssTransformProp", { link = "ColorsAqua" })
  hi("cssTransitionProp", { link = "ColorsAqua" })
  hi("cssPrintProp", { link = "ColorsAqua" })
  hi("cssPositioningProp", { link = "ColorsYellow" })
  hi("cssBoxProp", { link = "ColorsAqua" })
  hi("cssFontDescriptorProp", { link = "ColorsAqua" })
  hi("cssFlexibleBoxProp", { link = "ColorsAqua" })
  hi("cssBorderOutlineProp", { link = "ColorsAqua" })
  hi("cssBackgroundProp", { link = "ColorsAqua" })
  hi("cssMarginProp", { link = "ColorsAqua" })
  hi("cssListProp", { link = "ColorsAqua" })
  hi("cssTableProp", { link = "ColorsAqua" })
  hi("cssFontProp", { link = "ColorsAqua" })
  hi("cssPaddingProp", { link = "ColorsAqua" })
  hi("cssDimensionProp", { link = "ColorsAqua" })
  hi("cssRenderProp", { link = "ColorsAqua" })
  hi("cssColorProp", { link = "ColorsAqua" })
  hi("cssGeneratedContentProp", { link = "ColorsAqua" })
  hi("javaScriptBraces", { link = "ColorsFg1" })
  hi("javaScriptFunction", { link = "ColorsAqua" })
  hi("javaScriptIdentifier", { link = "ColorsRed" })
  hi("javaScriptMember", { link = "ColorsBlue" })
  hi("javaScriptNumber", { link = "ColorsPurple" })
  hi("javaScriptNull", { link = "ColorsPurple" })
  hi("javaScriptParens", { link = "ColorsFg3" })
  hi("typescriptReserved", { link = "ColorsAqua" })
  hi("typescriptLabel", { link = "ColorsAqua" })
  hi("typescriptFuncKeyword", { link = "ColorsAqua" })
  hi("typescriptIdentifier", { link = "ColorsOrange" })
  hi("typescriptBraces", { link = "ColorsFg1" })
  hi("typescriptEndColons", { link = "ColorsFg1" })
  hi("typescriptDOMObjects", { link = "ColorsFg1" })
  hi("typescriptAjaxMethods", { link = "ColorsFg1" })
  hi("typescriptLogicSymbols", { link = "ColorsFg1" })
  hi("typescriptDocSeeTag", { link = "Comment" })
  hi("typescriptDocParam", { link = "Comment" })
  hi("typescriptDocTags", { link = "vimCommentTitle" })
  hi("typescriptGlobalObjects", { link = "ColorsFg1" })
  hi("typescriptParens", { link = "ColorsFg3" })
  hi("typescriptOpSymbols", { link = "ColorsFg3" })
  hi("typescriptHtmlElemProperties", { link = "ColorsFg1" })
  hi("typescriptNull", { link = "ColorsPurple" })
  hi("typescriptInterpolationDelimiter", { link = "ColorsAqua" })
  hi("purescriptModuleKeyword", { link = "ColorsAqua" })
  hi("purescriptModuleName", { link = "ColorsFg1" })
  hi("purescriptWhere", { link = "ColorsAqua" })
  hi("purescriptDelimiter", { link = "ColorsFg4" })
  hi("purescriptType", { link = "ColorsFg1" })
  hi("purescriptImportKeyword", { link = "ColorsAqua" })
  hi("purescriptHidingKeyword", { link = "ColorsAqua" })
  hi("purescriptAsKeyword", { link = "ColorsAqua" })
  hi("purescriptStructure", { link = "ColorsAqua" })
  hi("purescriptOperator", { link = "ColorsBlue" })
  hi("purescriptTypeVar", { link = "ColorsFg1" })
  hi("purescriptConstructor", { link = "ColorsFg1" })
  hi("purescriptFunction", { link = "ColorsFg1" })
  hi("purescriptConditional", { link = "ColorsOrange" })
  hi("purescriptBacktick", { link = "ColorsOrange" })
  hi("coffeeExtendedOp", { link = "ColorsFg3" })
  hi("coffeeSpecialOp", { link = "ColorsFg3" })
  hi("coffeeCurly", { link = "ColorsOrange" })
  hi("coffeeParen", { link = "ColorsFg3" })
  hi("coffeeBracket", { link = "ColorsOrange" })
  hi("rubyStringDelimiter", { link = "ColorsGreen" })
  hi("rubyInterpolationDelimiter", { link = "ColorsAqua" })
  hi("rubyDefinedOperator", { link = "rubyKeyword" })
  hi("objcTypeModifier", { link = "ColorsRed" })
  hi("objcDirective", { link = "ColorsBlue" })
  hi("goDirective", { link = "ColorsAqua" })
  hi("goConstants", { link = "ColorsPurple" })
  hi("goDeclaration", { link = "ColorsRed" })
  hi("goDeclType", { link = "ColorsBlue" })
  hi("goBuiltins", { link = "ColorsOrange" })
  hi("luaIn", { link = "ColorsRed" })
  hi("luaFunction", { link = "ColorsAqua" })
  hi("luaTable", { link = "ColorsOrange" })
  hi("moonSpecialOp", { link = "ColorsFg3" })
  hi("moonExtendedOp", { link = "ColorsFg3" })
  hi("moonFunction", { link = "ColorsFg3" })
  hi("moonObject", { link = "ColorsYellow" })
  hi("javaAnnotation", { link = "ColorsBlue" })
  hi("javaDocTags", { link = "ColorsAqua" })
  hi("javaCommentTitle", { link = "vimCommentTitle" })
  hi("javaParen", { link = "ColorsFg3" })
  hi("javaParen1", { link = "ColorsFg3" })
  hi("javaParen2", { link = "ColorsFg3" })
  hi("javaParen3", { link = "ColorsFg3" })
  hi("javaParen4", { link = "ColorsFg3" })
  hi("javaParen5", { link = "ColorsFg3" })
  hi("javaOperator", { link = "ColorsOrange" })
  hi("javaVarArg", { link = "ColorsGreen" })
  hi("elixirDocString", { link = "Comment" })
  hi("elixirStringDelimiter", { link = "ColorsGreen" })
  hi("elixirInterpolationDelimiter", { link = "ColorsAqua" })
  hi("elixirModuleDeclaration", { link = "ColorsYellow" })
  hi("scalaNameDefinition", { link = "ColorsFg1" })
  hi("scalaCaseFollowing", { link = "ColorsFg1" })
  hi("scalaCapitalWord", { link = "ColorsFg1" })
  hi("scalaTypeExtension", { link = "ColorsFg1" })
  hi("scalaKeyword", { link = "ColorsRed" })
  hi("scalaKeywordModifier", { link = "ColorsRed" })
  hi("scalaSpecial", { link = "ColorsAqua" })
  hi("scalaOperator", { link = "ColorsFg1" })
  hi("scalaTypeDeclaration", { link = "ColorsYellow" })
  hi("scalaTypeTypePostDeclaration", { link = "ColorsYellow" })
  hi("scalaInstanceDeclaration", { link = "ColorsFg1" })
  hi("scalaInterpolation", { link = "ColorsAqua" })
  hi("markdownItalic", { link = "ColorsFg3" })
  hi("markdownBold", { link = "ColorsFg3" })
  hi("markdownBoldItalic", { link = "ColorsFg3" })
  hi("markdownH1", { link = "ColorsGreen" })
  hi("markdownH2", { link = "ColorsGreen" })
  hi("markdownH3", { link = "ColorsYellow" })
  hi("markdownH4", { link = "ColorsYellow" })
  hi("markdownH5", { link = "ColorsYellow" })
  hi("markdownH6", { link = "ColorsYellow" })
  hi("markdownCode", { link = "ColorsAqua" })
  hi("markdownCodeBlock", { link = "ColorsAqua" })
  hi("markdownCodeDelimiter", { link = "ColorsAqua" })
  hi("markdownBlockquote", { link = "ColorsGray" })
  hi("markdownListMarker", { link = "ColorsGray" })
  hi("markdownOrderedListMarker", { link = "ColorsGray" })
  hi("markdownRule", { link = "ColorsGray" })
  hi("markdownHeadingRule", { link = "ColorsGray" })
  hi("markdownUrlDelimiter", { link = "ColorsFg3" })
  hi("markdownLinkDelimiter", { link = "ColorsFg3" })
  hi("markdownLinkTextDelimiter", { link = "ColorsFg3" })
  hi("markdownHeadingDelimiter", { link = "ColorsOrange" })
  hi("markdownUrl", { link = "ColorsPurple" })
  hi("markdownUrlTitleDelimiter", { link = "ColorsGreen" })
  hi("markdownLinkText", { link = "ColorsGray" })
  hi("markdownIdDeclaration", { link = "markdownLinkText" })
  hi("haskellType", { link = "ColorsBlue" })
  hi("haskellIdentifier", { link = "ColorsAqua" })
  hi("haskellSeparator", { link = "ColorsFg4" })
  hi("haskellDelimiter", { link = "ColorsOrange" })
  hi("haskellOperators", { link = "ColorsPurple" })
  hi("haskellBacktick", { link = "ColorsOrange" })
  hi("haskellStatement", { link = "ColorsPurple" })
  hi("haskellConditional", { link = "ColorsPurple" })
  hi("haskellLet", { link = "ColorsRed" })
  hi("haskellDefault", { link = "ColorsRed" })
  hi("haskellWhere", { link = "ColorsRed" })
  hi("haskellBottom", { link = "ColorsRed" })
  hi("haskellImportKeywords", { link = "ColorsPurple" })
  hi("haskellDeclKeyword", { link = "ColorsOrange" })
  hi("haskellDecl", { link = "ColorsOrange" })
  hi("haskellDeriving", { link = "ColorsPurple" })
  hi("haskellAssocType", { link = "ColorsAqua" })
  hi("haskellNumber", { link = "ColorsAqua" })
  hi("haskellPragma", { link = "ColorsRed" })
  hi("haskellTH", { link = "ColorsAqua" })
  hi("haskellForeignKeywords", { link = "ColorsGreen" })
  hi("haskellKeyword", { link = "ColorsRed" })
  hi("haskellFloat", { link = "ColorsAqua" })
  hi("haskellInfix", { link = "ColorsPurple" })
  hi("haskellQuote", { link = "ColorsGreen" })
  hi("haskellShebang", { link = "ColorsYellow" })
  hi("haskellLiquid", { link = "ColorsPurple" })
  hi("haskellQuasiQuoted", { link = "ColorsBlue" })
  hi("haskellRecursiveDo", { link = "ColorsPurple" })
  hi("haskellQuotedType", { link = "ColorsRed" })
  hi("haskellPreProc", { link = "ColorsFg4" })
  hi("haskellTypeRoles", { link = "ColorsRed" })
  hi("haskellTypeForall", { link = "ColorsRed" })
  hi("haskellPatternKeyword", { link = "ColorsBlue" })
  hi("jsonKeyword", { link = "ColorsGreen" })
  hi("jsonQuote", { link = "ColorsGreen" })
  hi("jsonBraces", { link = "ColorsFg1" })
  hi("jsonString", { link = "ColorsFg1" })
  hi("mailQuoted1", { link = "ColorsAqua" })
  hi("mailQuoted2", { link = "ColorsPurple" })
  hi("mailQuoted3", { link = "ColorsYellow" })
  hi("mailQuoted4", { link = "ColorsGreen" })
  hi("mailQuoted5", { link = "ColorsRed" })
  hi("mailQuoted6", { link = "ColorsOrange" })
  hi("mailSignature", { link = "Comment" })
  hi("csBraces", { link = "ColorsFg1" })
  hi("csEndColon", { link = "ColorsFg1" })
  hi("csLogicSymbols", { link = "ColorsFg1" })
  hi("csParens", { link = "ColorsFg3" })
  hi("csOpSymbols", { link = "ColorsFg3" })
  hi("csInterpolationDelimiter", { link = "ColorsFg3" })
  hi("csInterpolationAlignDel", { link = "ColorsAqua" })
  hi("csInterpolationFormat", { link = "ColorsAqua" })
  hi("csInterpolationFormatDel", { link = "ColorsAqua" })
  hi("rustSigil", { link = "ColorsOrange" })
  hi("rustEscape", { link = "ColorsAqua" })
  hi("rustStringContinuation", { link = "ColorsAqua" })
  hi("rustEnum", { link = "ColorsAqua" })
  hi("rustStructure", { link = "ColorsAqua" })
  hi("rustModPathSep", { link = "ColorsFg2" })
  hi("rustCommentLineDoc", { link = "Comment" })
  hi("rustDefault", { link = "ColorsAqua" })
  hi("ocamlOperator", { link = "ColorsFg1" })
  hi("ocamlKeyChar", { link = "ColorsOrange" })
  hi("ocamlArrow", { link = "ColorsOrange" })
  hi("ocamlInfixOpKeyword", { link = "ColorsRed" })
  hi("ocamlConstructor", { link = "ColorsOrange" })

  -- treesitter
  hi("@comment", { link = "Comment" })
  hi("@none", { bg = nil, fg = nil })
  hi("@preproc", { link = "PreProc" })
  hi("@define", { link = "Define" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation.delimiter", { link = "Delimiter" })
  hi("@punctuation.bracket", { link = "Delimiter" })
  hi("@punctuation.special", { link = "Delimiter" })
  hi("@string", { link = "String" })
  hi("@string.regex", { link = "String" })
  hi("@string.regexp", { link = "String" })
  hi("@string.escape", { link = "SpecialChar" })
  hi("@string.special", { link = "SpecialChar" })
  hi("@string.special.path", { link = "Underlined" })
  hi("@string.special.symbol", { link = "Identifier" })
  hi("@string.special.url", { link = "Underlined" })
  hi("@character", { link = "Character" })
  hi("@character.special", { link = "SpecialChar" })
  hi("@boolean", { link = "Boolean" })
  hi("@number", { link = "Number" })
  hi("@number.float", { link = "Float" })
  hi("@float", { link = "Float" })
  hi("@function", { link = "Function" })
  hi("@function.builtin", { link = "Special" })
  hi("@function.call", { link = "Function" })
  hi("@function.macro", { link = "Macro" })
  hi("@function.method", { link = "Function" })
  hi("@method", { link = "Function" })
  hi("@method.call", { link = "Function" })
  hi("@constructor", { link = "Special" })
  hi("@parameter", { link = "Identifier" })
  hi("@keyword", { link = "Keyword" })
  hi("@keyword.conditional", { link = "Conditional" })
  hi("@keyword.debug", { link = "Debug" })
  hi("@keyword.directive", { link = "PreProc" })
  hi("@keyword.directive.define", { link = "Define" })
  hi("@keyword.exception", { link = "Exception" })
  hi("@keyword.function", { link = "Keyword" })
  hi("@keyword.import", { link = "Include" })
  hi("@keyword.operator", { link = "ColorsRed" })
  hi("@keyword.repeat", { link = "Repeat" })
  hi("@keyword.return", { link = "Keyword" })
  hi("@keyword.storage", { link = "StorageClass" })
  hi("@conditional", { link = "Conditional" })
  hi("@repeat", { link = "Repeat" })
  hi("@debug", { link = "Debug" })
  hi("@label", { link = "Label" })
  hi("@include", { link = "Include" })
  hi("@exception", { link = "Exception" })
  hi("@type", { link = "Type" })
  hi("@type.builtin", { link = "Type" })
  hi("@type.definition", { link = "Typedef" })
  hi("@type.qualifier", { link = "Type" })
  hi("@storageclass", { link = "StorageClass" })
  hi("@attribute", { link = "PreProc" })
  hi("@field", { link = "Identifier" })
  hi("@property", { link = "Identifier" })
  hi("@variable", { link = "ColorsFg1" })
  hi("@variable.builtin", { link = "Special" })
  hi("@variable.member", { link = "Identifier" })
  hi("@variable.parameter", { link = "Identifier" })
  hi("@constant", { link = "Constant" })
  hi("@constant.builtin", { link = "Special" })
  hi("@constant.macro", { link = "Define" })
  hi("@markup", { link = "ColorsFg1" })
  hi("@markup.strong", {})
  hi("@markup.italic", { link = "@text.emphasis" })
  hi("@markup.underline", {})
  hi("@markup.strikethrough", {})
  hi("@markup.heading", { link = "Title" })
  hi("@markup.raw", { link = "String" })
  hi("@markup.math", { link = "Special" })
  hi("@markup.environment", { link = "Macro" })
  hi("@markup.environment.name", { link = "Type" })
  hi("@markup.link", { link = "Underlined" })
  hi("@markup.link.label", { link = "SpecialChar" })
  hi("@markup.list", { link = "Delimiter" })
  hi("@markup.list.checked", { link = "ColorsGreen" })
  hi("@markup.list.unchecked", { link = "ColorsGray" })
  hi("@comment.todo", { link = "Todo" })
  hi("@comment.note", { link = "SpecialComment" })
  hi("@comment.warning", { link = "WarningMsg" })
  hi("@comment.error", { link = "ErrorMsg" })
  hi("@diff.plus", { link = "diffAdded" })
  hi("@diff.minus", { link = "diffRemoved" })
  hi("@diff.delta", { link = "diffChanged" })
  hi("@module", { link = "ColorsFg1" })
  hi("@namespace", { link = "ColorsFg1" })
  hi("@symbol", { link = "Identifier" })
  hi("@text", { link = "ColorsFg1" })
  hi("@text.strong", {})
  hi("@text.emphasis", {})
  hi("@text.underline", {})
  hi("@text.strike", {})
  hi("@text.title", { link = "Title" })
  hi("@text.literal", { link = "String" })
  hi("@text.uri", { link = "Underlined" })
  hi("@text.math", { link = "Special" })
  hi("@text.environment", { link = "Macro" })
  hi("@text.environment.name", { link = "Type" })
  hi("@text.reference", { link = "Constant" })
  hi("@text.todo", { link = "Todo" })
  hi("@text.todo.checked", { link = "ColorsGreen" })
  hi("@text.todo.unchecked", { link = "ColorsGray" })
  hi("@text.note", { link = "SpecialComment" })
  hi("@text.note.comment", { fg = p.purple })
  hi("@text.warning", { link = "WarningMsg" })
  hi("@text.danger", { link = "ErrorMsg" })
  hi("@text.danger.comment", { fg = p.fg0, bg = p.red })
  hi("@text.diff.add", { link = "diffAdded" })
  hi("@text.diff.delete", { link = "diffRemoved" })
  hi("@tag", { link = "Tag" })
  hi("@tag.attribute", { link = "Identifier" })
  hi("@tag.delimiter", { link = "Delimiter" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@macro", { link = "Macro" })
  hi("@structure", { link = "Structure" })
  hi("@lsp.type.class", { link = "@type" })
  hi("@lsp.type.comment", { link = "@comment" })
  hi("@lsp.type.decorator", { link = "@macro" })
  hi("@lsp.type.enum", { link = "@type" })
  hi("@lsp.type.enumMember", { link = "@constant" })
  hi("@lsp.type.function", { link = "@function" })
  hi("@lsp.type.interface", { link = "@constructor" })
  hi("@lsp.type.macro", { link = "@macro" })
  hi("@lsp.type.method", { link = "@method" })
  hi("@lsp.type.modifier.java", { link = "@keyword.type.java" })
  hi("@lsp.type.namespace", { link = "@namespace" })
  hi("@lsp.type.parameter", { link = "@parameter" })
  hi("@lsp.type.property", { link = "@property" })
  hi("@lsp.type.struct", { link = "@type" })
  hi("@lsp.type.type", { link = "@type" })
  hi("@lsp.type.typeParameter", { link = "@type.definition" })
  hi("@lsp.type.variable", { link = "@variable" })

  -- gitcommit
  hi("gitcommitBranch", { link = "ColorsFg1" })
  hi("gitcommitComment", { link = "Comment" })
  hi("gitcommitDiscarded", { link = "Comment" })
  hi("gitcommitDiscardedFile", { link = "ColorsRed" })
  hi("gitcommitDiscardedType", { link = "ColorsAqua" })
  hi("gitcommitHeader", { link = "ColorsPurple" })
  hi("gitcommitOverflow", { link = "ColorsFg1" })
  hi("gitcommitSelected", { link = "Comment" })
  hi("gitcommitSelectedFile", { link = "ColorsGreen" })
  hi("gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi("gitcommitSummary", { link = "ColorsGreen" })
  hi("gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi("gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi("gitcommitUntracked", { link = "Comment" })
  hi("gitcommitUntrackedFile", { link = "ColorsAqua" })

  -- patch diff
  hi("diffAdded", { link = "DiffAdd" })
  hi("diffRemoved", { link = "DiffDelete" })
  hi("diffChanged", { link = "DiffChange" })
  hi("diffFile", { link = "ColorsOrange" })
  hi("diffNewFile", { link = "ColorsYellow" })
  hi("diffOldFile", { link = "ColorsOrange" })
  hi("diffLine", { link = "ColorsBlue" })
  hi("diffIndexLine", { link = "diffChanged" })
  hi("Added", { link = "ColorsGreen" })
  hi("Changed", { link = "ColorsOrange" })
  hi("Removed", { link = "ColorsRed" })

  -- lewis6991/gitsigns.nvim
  hi("GitSignsAdd", { link = "ColorsGreen" })
  hi("GitSignsChange", { link = "ColorsOrange" })
  hi("GitSignsDelete", { link = "ColorsRed" })

  -- netrw
  hi("netrwDir", { link = "ColorsAqua" })
  hi("netrwClassify", { link = "ColorsAqua" })
  hi("netrwLink", { link = "ColorsGray" })
  hi("netrwSymLink", { link = "ColorsFg1" })
  hi("netrwExe", { link = "ColorsYellow" })
  hi("netrwComment", { link = "ColorsGray" })
  hi("netrwList", { link = "ColorsBlue" })
  hi("netrwHelpCmd", { link = "ColorsAqua" })
  hi("netrwCmdSep", { link = "ColorsFg3" })
  hi("netrwVersion", { link = "ColorsGreen" })

  -- hrsh7th/nvim-cmp
  hi("CmpItemAbbr", { link = "ColorsFg0" })
  hi("CmpItemAbbrDeprecated", { link = "ColorsFg1" })
  hi("CmpItemAbbrMatch", { link = "ColorsBlue" })
  hi("CmpItemAbbrMatchFuzzy", { link = "ColorsBlue" })
  hi("CmpItemMenu", { link = "ColorsGray" })
  hi("CmpItemKindText", { link = "ColorsOrange" })
  hi("CmpItemKindVariable", { link = "ColorsOrange" })
  hi("CmpItemKindMethod", { link = "ColorsBlue" })
  hi("CmpItemKindFunction", { link = "ColorsBlue" })
  hi("CmpItemKindConstructor", { link = "ColorsYellow" })
  hi("CmpItemKindUnit", { link = "ColorsBlue" })
  hi("CmpItemKindField", { link = "ColorsBlue" })
  hi("CmpItemKindClass", { link = "ColorsYellow" })
  hi("CmpItemKindInterface", { link = "ColorsYellow" })
  hi("CmpItemKindModule", { link = "ColorsBlue" })
  hi("CmpItemKindProperty", { link = "ColorsBlue" })
  hi("CmpItemKindValue", { link = "ColorsOrange" })
  hi("CmpItemKindEnum", { link = "ColorsYellow" })
  hi("CmpItemKindOperator", { link = "ColorsYellow" })
  hi("CmpItemKindKeyword", { link = "ColorsPurple" })
  hi("CmpItemKindEvent", { link = "ColorsPurple" })
  hi("CmpItemKindReference", { link = "ColorsPurple" })
  hi("CmpItemKindColor", { link = "ColorsPurple" })
  hi("CmpItemKindSnippet", { link = "ColorsGreen" })
  hi("CmpItemKindFile", { link = "ColorsBlue" })
  hi("CmpItemKindFolder", { link = "ColorsBlue" })
  hi("CmpItemKindEnumMember", { link = "ColorsAqua" })
  hi("CmpItemKindConstant", { link = "ColorsOrange" })
  hi("CmpItemKindStruct", { link = "ColorsYellow" })
  hi("CmpItemKindTypeParameter", { link = "ColorsYellow" })
  hi("CmpItemKindTextIcon", { link = "CmpItemKindText" })
  hi("CmpItemKindVariableIcon", { link = "CmpItemKindVariable" })
  hi("CmpItemKindMethodIcon", { link = "CmpItemKindMethod" })
  hi("CmpItemKindFunctionIcon", { link = "CmpItemKindFunction" })
  hi("CmpItemKindConstructorIcon", { link = "CmpItemKindConstructor" })
  hi("CmpItemKindUnitIcon", { link = "CmpItemKindUnit" })
  hi("CmpItemKindFieldIcon", { link = "CmpItemKindField" })
  hi("CmpItemKindClassIcon", { link = "CmpItemKindClass" })
  hi("CmpItemKindInterfaceIcon", { link = "CmpItemKindInterface" })
  hi("CmpItemKindModuleIcon", { link = "CmpItemKindModule" })
  hi("CmpItemKindPropertyIcon", { link = "CmpItemKindProperty" })
  hi("CmpItemKindValueIcon", { link = "CmpItemKindValue" })
  hi("CmpItemKindEnumIcon", { link = "CmpItemKindEnum" })
  hi("CmpItemKindOperatorIcon", { link = "CmpItemKindOperator" })
  hi("CmpItemKindKeywordIcon", { link = "CmpItemKindKeyword" })
  hi("CmpItemKindEventIcon", { link = "CmpItemKindEvent" })
  hi("CmpItemKindReferenceIcon", { link = "CmpItemKindReference" })
  hi("CmpItemKindColorIcon", { link = "CmpItemKindColor" })
  hi("CmpItemKindSnippetIcon", { link = "CmpItemKindSnippet" })
  hi("CmpItemKindFileIcon", { link = "CmpItemKindFile" })
  hi("CmpItemKindFolderIcon", { link = "CmpItemKindFolder" })
  hi("CmpItemKindEnumMemberIcon", { link = "CmpItemKindEnumMember" })
  hi("CmpItemKindConstantIcon", { link = "CmpItemKindConstant" })
  hi("CmpItemKindStructIcon", { link = "CmpItemKindStruct" })
  hi("CmpItemKindTypeParameterIcon", { link = "CmpItemKindTypeParameter" })
  hi("CmpCursorLine", { fg = p.bg0, bg = p.blue })

  -- nvim-mini/mini.nvim
  hi("MiniHipatternsFixme", { fg = p.bg0, bg = p.red })
  hi("MiniHipatternsHack", { fg = p.bg0, bg = p.yellow })
  hi("MiniHipatternsNote", { fg = p.bg0, bg = p.blue })
  hi("MiniHipatternsTodo", { fg = p.bg0, bg = p.aqua })
  hi("MiniIconsAzure", { link = "ColorsBlue" })
  hi("MiniIconsBlue", { link = "ColorsBlue" })
  hi("MiniIconsCyan", { link = "ColorsAqua" })
  hi("MiniIconsGreen", { link = "ColorsGreen" })
  hi("MiniIconsGrey", { link = "ColorsFg0" })
  hi("MiniIconsOrange", { link = "ColorsOrange" })
  hi("MiniIconsPurple", { link = "ColorsPurple" })
  hi("MiniIconsRed", { link = "ColorsRed" })
  hi("MiniIconsYellow", { link = "ColorsYellow" })
  hi("MiniIndentscopeSymbol", { link = "ColorsGray" })
  hi("MiniIndentscopeSymbolOff", { link = "ColorsYellow" })
  hi("MiniJump", { link = "ColorsAqua" })
  hi("MiniJump2dDim", { link = "ColorsGray" })
  hi("MiniJump2dSpot", { fg = p.bg0, bg = p.aqua, nocombine = true })
  hi("MiniJump2dSpotAhead", { link = "MiniJump2dSpot" })
  hi("MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi("MiniNotifyBorder", { link = "FloatBorder" })
  hi("MiniNotifyNormal", { link = "NormalFloat" })
  hi("MiniNotifyTitle", { link = "FloatTitle" })
  hi("MiniPickBorder", { link = "FloatBorder" })
  hi("MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
  hi("MiniPickBorderText", { link = "FloatTitle" })
  hi("MiniPickIconDirectory", { link = "Directory" })
  hi("MiniPickIconFile", { link = "MiniPickNormal" })
  hi("MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi("MiniPickMatchCurrent", { bg = p.bg2 })
  hi("MiniPickMatchMarked", { link = "Visual" })
  hi("MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi("MiniPickNormal", { link = "NormalFloat" })
  hi("MiniPickPreviewLine", { link = "CursorLine" })
  hi("MiniPickPreviewRegion", { link = "IncSearch" })
  hi("MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
  hi("MiniStarterCurrent", { nocombine = true })
  hi("MiniStarterFooter", { link = "ColorsGray" })
  hi("MiniStarterHeader", { link = "Title" })
  hi("MiniStarterInactive", { link = "Comment" })
  hi("MiniStarterItem", { link = "Normal" })
  hi("MiniStarterItemBullet", { link = "Delimiter" })
  hi("MiniStarterItemPrefix", { link = "WarningMsg" })
  hi("MiniStarterSection", { link = "Delimiter" })
  hi("MiniStarterQuery", { link = "MoreMsg" })
  hi("MiniStatuslineInactive", { link = "StatusLineNC" })
  hi("MiniStatuslineDevinfo", { link = "StatusLine" })
  hi("MiniStatuslineFileinfo", { link = "StatusLine" })
  hi("MiniStatuslineFilename", { link = "StatusLineNC" })
  hi("MiniStatuslineModeCommand", { fg = p.bg0, bg = p.purple })
  hi("MiniStatuslineModeInsert", { fg = p.bg0, bg = p.green })
  hi("MiniStatuslineModeNormal", { fg = p.bg0, bg = p.fg1 })
  hi("MiniStatuslineModeOther", { fg = p.bg0, bg = p.aqua })
  hi("MiniStatuslineModeReplace", { fg = p.bg0, bg = p.yellow })
  hi("MiniStatuslineModeVisual", { fg = p.bg0, bg = p.red })
  hi("MiniSurround", { link = "IncSearch" })
  hi("MiniTablineCurrent", { fg = p.green, bg = p.bg0 })
  hi("MiniTablineFill", { link = "TabLineFill" })
  hi("MiniTablineHidden", { fg = p.bg4, bg = nil })
  hi("MiniTablineModifiedCurrent", { fg = p.bg1, bg = p.green })
  hi("MiniTablineModifiedHidden", { fg = p.bg1, bg = p.bg4 })
  hi("MiniTablineModifiedVisible", { fg = p.bg1, bg = p.fg1 })
  hi("MiniTablineTabpagesection", { link = "Search" })
  hi("MiniTablineVisible", { fg = p.fg1, bg = p.bg0 })

  -- nvim-treesitter/nvim-treesitter-context
  hi("TreesitterContext", { link = "NormalFloat" })
  hi("TreesitterContextBottom", { fg = nil })
  hi("TreesitterContextLineNumber", { link = "LineNr" })
  hi("TreesitterContextLineNumberBottom", { link = "WinSeparator" })
  hi("TreesitterContextSeparator", { link = "WinSeparator" })
end


return Colors
