format = "$cmd_duration$directory$git_branch$character"
right_format = ""
add_newline = false


[character]
format = "$symbol"
success_symbol = "[  ](fg:blue)"
error_symbol = "[  ](fg:red)"


[cmd_duration]
min_time = 0
format = "[](fg:yellow bold)[󰪢 $duration](fg:#1e1e2e bg:yellow bold)[](fg:yellow bold)"


[directory]
format = " 󰜥 [](fg:green bold)[󰉋 $path](fg:#1e1e2e bg:green bold)[](fg:green bold)"
home_symbol = "  "
read_only = ""
truncation_length = 3
truncation_symbol = ""
truncate_to_repo = false


[git_branch]
format = " 󰜥 [](fg:cyan bold)[󰘬 $branch](fg:#1e1e2e bg:cyan bold)[](fg:cyan bold)"
truncation_length = 12
truncation_symbol = ".."
