# [colors.primary]
# background = "#1d2021"
# foreground = "#fbf1c7"
#
#
# [colors.normal]
# black = '#3c3836'
# red = '#ea6962'
# green = '#a9b665'
# yellow = '#d8a657'
# blue = '#7daea3'
# magenta = '#d3869b'
# cyan = '#89b482'
# white = '#d4be98'
#
#
# [colors.bright]
# black = "#3c3836"
# red = "#ea6962"
# green = "#a9b665"
# yellow = "#d8a657"
# blue = '#7daea3'
# magenta = '#d3869b'
# cyan = '#89b482'
# white = '#d4be98'
#
#
# [colors.selection]
# text = "#d4be98"
# background = "#3c3836"
#
# [colors.cursor]
# text = "#1d2021"
# background = "#fbf1c7"

# Colors (Everforest Dark Hard)

# [colors.primary]
# background = '#272e33'
# foreground = '#d3c6aa'
#
# [colors.normal]
# black   = '#414b50'
# red     = '#e67e80'
# green   = '#a7c080'
# yellow  = '#dbbc7f'
# blue    = '#7fbbb3'
# magenta = '#d699b6'
# cyan    = '#83c092'
# white   = '#d3c6aa'
#
# [colors.bright]
# black   = '#414b50'
# red     = '#e67e80'
# green   = '#a7c080'
# yellow  = '#dbbc7f'
# blue    = '#7fbbb3'
# magenta = '#d699b6'
# cyan    = '#83c092'
# white   = '#d3c6aa'
#
# [colors.selection]
# background = '#414b50'
# text       = '#d3c6aa'
#
# [colors.cursor]
# background = "#d3c6aa"
# text = "#272e33"

# [colors.search.matches]
# background = '#a7c080'
# foreground = '#272e33'

# [colors.search.focused_match]
# background = '#e67e80'
# foreground = '#272e33'

# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'

[font]
size = 19
builtin_box_drawing = true
normal.family = "JetBrains Mono NF"
normal.style = "Bold"


[cursor]
style.shape = "Block"
style.blinking = "Never"


[window]
padding.x = 5
padding.y = 5
decorations = "None"
startup_mode = "Maximized"
