# LDFLAGS  = ${LIBS}
#
# clean:
# 	rm -f dwm ${OBJ} dwm-${VERSION}.tar.gz
# 	rm -f dwm-msg
#
# dist: clean
# 	mkdir -p dwm-${VERSION}
# 	cp -R LICENSE Makefile README config.def.h config.mk\
# 		dwm.1 drw.h util.h ${SRC} dwm.png transient.c dwm-${VERSION}
# 	tar -cf dwm-${VERSION}.tar dwm-${VERSION}
# 	gzip dwm-${VERSION}.tar
# 	rm -rf dwm-${VERSION}
#
# install: all
# 	mkdir -p ${DESTDIR}${PREFIX}/bin
# 	cp -f dwm ${DESTDIR}${PREFIX}/bin
# ifdef YAJLLIBS
# 	cp -f dwm-msg ${DESTDIR}${PREFIX}/bin
# endif
# 	chmod 755 ${DESTDIR}${PREFIX}/bin/dwm
# ifdef YAJLLIBS
# 	chmod 755 ${DESTDIR}${PREFIX}/bin/dwm-msg
# endif
# 	mkdir -p ${DESTDIR}${PREFIX}/bin/
# 	# test -f ${DESTDIR}${PREFIX}/bin/start.sh || cp -n ./assets/start.sh ${DESTDIR}${PREFIX}/bin
# 	cp ./assets/start.sh ${DESTDIR}${PREFIX}/bin
# 	chmod 755 ${DESTDIR}${PREFIX}/bin/start.sh
# 	# sed "s/VERSION/${VERSION}/g" < dwm.1 > ${DESTDIR}${MANPREFIX}/man1/dwm.1
# 	# chmod 644 ${DESTDIR}${MANPREFIX}/man1/dwm.1
# 	mkdir -p ${DESTDIR}/usr/share/xsessions
# 	# test -f ${DESTDIR}/usr/share/xsessions/dwm.desktop || cp -n ./assets/dwm.desktop ${DESTDIR}/usr/share/xsessions
# 	cp ./assets/dwm.desktop ${DESTDIR}/usr/share/xsessions
# 	chmod 644 ${DESTDIR}/usr/share/xsessions/dwm.desktop
#
# uninstall:
# 	rm -f ${DESTDIR}${PREFIX}/bin/dwm\
# 		${DESTDIR}${MANPREFIX}/man1/dwm.1\
# 		${DESTDIR}${PREFIX}/share/xsessions/dwm.desktop
#
# .PHONY: all clean dist install uninstall

version := "6.8"

bin_prefix := "/usr/local/bin"
session_prefix := "/usr/share/xsessions"

x11inc := "/usr/X11R6/include"
x11lib := "/usr/X11R6/lib"

xinerama_libs := "-lXinerama"
xinerama_flags := "-DXINERAMA"

freetype_libs := "-lfontconfig -lXft"
freetype_inc := "/usr/include/freetype2"

incs := "-I" + x11inc + " -I" + freetype_inc
libs := "-L" + x11lib + " -lX11 " + xinerama_libs + " " + freetype_libs

cppflags := "-D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700L -DVERSION=\"6.8\" " + xinerama_flags
cflags := "-std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os " + incs + " " + cppflags

cc := "cc"

default:
  @just --list

config:
  @test -f config.h || cp config.def.h config.h

build: config
  @{{cc}} -c {{cflags}} drw.c
  @{{cc}} -c {{cflags}} util.c
  @{{cc}} -c {{cflags}} dwm.c
  @{{cc}} -o dwm drw.o util.o dwm.o {{libs}}
